### ISSUE TITLE
The code of docs seems wrong

### ISSUE THREAD

**Issue by Hanggi** [nestjs/docs.nestjs.com#1011]
https://docs.nestjs.com/techniques/task-scheduling#dynamic-intervals

the code of addInterval function is an error code.

the seconds should be number, and the callback function miss '('

Thank you.

**Comment by kamilmysliwiec** [comment]
It will be fixed as part of this PR https://github.com/nestjs/docs.nestjs.com/pull/1012/files Thanks for reporting
