### ISSUE TITLE
Using FormData in End to End testing

### ISSUE THREAD

**Issue by JamesLMilner** [nestjs/docs.nestjs.com#1064]
## Is your feature request related to a problem? Please describe.
It would be great if there was a explanation of how to send `FormData` in an E2E test within the Nest.js documention. Firstly I'm not sure if this is actually possible, as I tried it using JSDOM `FormData` and the DTO could be parsed to the correct types as it is with the live API from the frontend/API testing client (Insomnia). As such there is a chance this is bug as well as an undocumented feature, here's what I was doing:

```typescript
const { FormData, File, Blob } = new JSDOM(``, { runScripts: 'dangerously' }).window;
const formData = new FormData();
const catImageFile = new File([new Blob([])], 'filename');
formData.append('file', floorplanImageFile);
formData.append('catName', 'Topcat');
```

## Describe the solution you'd like
```typescript
 it('POST formData to cat endpoit', () => {

    // Imported from JSDOM
    const formData = new FormData();

    formData.append('name', 'Topcat');

    return request(app.getHttpServer())
        .post(`/api/v1/cat`)
        .send(formData)
        .expect(200)

 })
```
## Teachability, Documentation, Adoption, Migration Strategy
Being able to find a demonstration of how to do this in the following section would be invaluable:

https://docs.nestjs.com/fundamentals/testing#end-to-end-testing

## What is the motivation / use case for changing the behavior?
Sending `FormData` is a very common behaviour for any web app that requires file uploads. Most larger apps nowadays will have some form of file upload element too them

**Comment by JamesLMilner** [comment]
Even if it's not explicitly in the documentation yet, is there a recommended way to do this? If I can get a good solution I am happy to write it up and make a PR to the docs.

**Comment by kamilmysliwiec** [comment]
`supertest` is using the `superagent` lib. You can find more information on multipart requests here https://visionmedia.github.io/superagent/#multipart-requests
