### ISSUE TITLE
Add typegoose example to Mongo chapter

### ISSUE THREAD

**Issue by DaveLomber** [nestjs/docs.nestjs.com#1066]
There is a Serialization doc guide 
https://docs.nestjs.com/techniques/serialization

which works with a term 'Entity' which is a TS class

But, when have a Nest.js app integrated with Mongo (Mongoose) - the thing that is used  is a TS interface, not a class. 
Hence it's not clear how to use Serialization in a case of Mongoose integration. 

It's either should be an explanation on Serialization doc guide re how to use it with Mongoose or a clear hint that it's not valid for a case with Mongoose, e.g. a hint to use something like this instead https://medium.com/@contactsunny/hide-properties-of-mongoose-objects-in-node-js-json-responses-a5437a5dbec2

**Comment by kamilmysliwiec** [comment]
Typegoose is no longer needed in the context of NestJS. You can use `@nestjs/mongoose` decorators instead https://github.com/nestjs/docs.nestjs.com/issues/1230
