### ISSUE TITLE
Missing DTO example in controllers documentation

### ISSUE THREAD

**Issue by AnthonyWebDev** [nestjs/docs.nestjs.com#1183]
Hi,

As I am learning NestJS I was reading the documentation and found an empty slot where I should find a DTO example.

![Screenshot 2020-04-21 at 14 47 43](https://user-images.githubusercontent.com/62936624/79867816-3a765280-83df-11ea-8efc-40987df87ff6.png)

I guess it's a small omission. Would have PR something if I knew what was a DTO 😅 !

Thanks.

**Comment by kamilmysliwiec** [comment]
It looks like a regression. Let me temporarily revert a PR which caused this. Thanks for reporting!
