### ISSUE TITLE
Who can tell me where it is

### ISSUE THREAD

**Issue by cuiyimeng** [nestjs/docs.nestjs.com#1186]
in https://docs.nestjs.com/techniques/authentication#jwt-functionality 
<code>
import { Controller, Request, Post, UseGuards } from '@nestjs/common';
import { LocalAuthGuard } from './auth/local-auth.guard';
import { AuthService } from './auth/auth.service';

@Controller()
export class AppController {
  constructor(private authService: AuthService) {}

  @UseGuards(LocalAuthGuard)
  @Post('auth/login')
  async login(@Request() req) {
    return this.authService.login(req.user);
  }
}
</code>

who can tell me where is LocalAuthGuard

**Comment by kamilmysliwiec** [comment]
https://docs.nestjs.com/techniques/authentication#login-route

![image](https://user-images.githubusercontent.com/23244943/79949127-59272880-8475-11ea-955b-ac628298c0c5.png)
