### ISSUE TITLE
GraphQL Federation example documentation is misleading

### ISSUE THREAD

**Issue by Maddimax** [nestjs/docs.nestjs.com#1216]
## The Problem
I had an issue understanding https://docs.nestjs.com/graphql/federation#federated-example-posts as its missing critical information.

The example in "Federated example: Posts" shows:

```
extend type User @key(fields: "id") {
  id: ID! @external
  posts: [Post]
}
```

but then never explains how to provide the data for the "posts" field.
To me it seemed initially as if the query "getPosts" was supposed to provide the data.

## The solution ?

I would like to add 
```
@Resolver('User')
export class UserInPostsResolver {
  @ResolveField('posts')
  posts(@Parent() user: any) {
    return this.postsService.find({ where: { userId: user.id } })
  }
}
```
to the "Federated example: Posts" section to show users how to implement it.

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by Maddimax** [comment]
It was actually added in the meantime: https://github.com/nestjs/docs.nestjs.com/pull/1213

I'll close this issue.
