### ISSUE TITLE
Clarify middleware execution order

### ISSUE THREAD

**Issue by choyg** [nestjs/docs.nestjs.com#1248]
## Is your feature request related to a problem? Please describe.
Middleware order is described [here](https://docs.nestjs.com/middleware#multiple-middleware) for a single module. However, it is unclear how order is affected when an imported module also contains middleware. 

For example, consider the following modules where `AppModule` imports `MiddlewareModule` - what would be expected behavior? I'd personally expect AppModule middleware to apply first but this case is unspecified in documentation.
``` ts
@Module()
export class MiddlewareModule implements NestModule {
  configure(consumer: MiddlewareConsumer) {
    consumer
      .apply(Middleware)
      .forRoutes(...)
  }
}

@Module({
  imports: [MiddlewareModule]
})
export class AppModule implements NestModule {
  configure(consumer: MiddlewareConsumer) {
    consumer
      .apply(GlobalMiddleware)
      .forRoutes(...)
  }
}
```

**Comment by kamilmysliwiec** [comment]
@jmcdo29 would you like to create a PR to this issue? As far as I remember, this particular chapter (request-lifecycle) was created by you so I don't want to mess up 😅

**Comment by jmcdo29** [comment]
@kamilmysliwiec yeah I can try to get around to it. Shouldn't be too hard to add the mention in there. Was waiting to see if a community member wanted to take or first.
