### ISSUE TITLE
Cannot get HMR working with nestjs + typeorm + graphql

### ISSUE THREAD

**Issue by brandon-leapyear** [nestjs/docs.nestjs.com#1299]
## Current behavior
I have a NestJS project with TypeORM + Graphql configured
```
@Module({
  imports: [
    GraphQLFederationModule.forRoot({
      autoSchemaFile: path.join(process.cwd(), 'src/schema.gql'),
      context: ({ req }) => ({ req }),
    }),
    TypeOrmModule.forRootAsync({
      useClass: TypeOrmConfigService,
      imports: [ConfigModule],
    }),
    ...
  ],
  ...
})
export class AppModule {}
```
I followed the instructions in the [guide](https://docs.nestjs.com/recipes/hot-reload), but when making a change to one of my `.resolver.ts` files, I see one of two errors:
```
AlreadyHasActiveConnectionError: Cannot create a new connection named "default", 
because connection with such name already exist and it now has an active connection session.
```
or
```
(node:45219) UnhandledPromiseRejectionWarning: Error: Schema must contain 
uniquely named types but contains multiple types named "User".
```
For the first case, I found this [StackOverflow](https://stackoverflow.com/questions/54842295/how-to-wait-for-app-to-close-before-starting-a-new-instance-with-webpack-hot-mod) post, but adding `keepConnectionAlive` didn't help for me. (I added it to the object returned by `TypeOrmConfigService.createTypeOrmOptions()`). It seems to be better by doing
```ts
  if (module.hot) {
    module.hot.accept()
    module.hot.dispose(async () => {
      await getConnection().close()
      await app.close()
    })
  }
```
but I still get the graphql error, plus a new error:
```
(node:46024) UnhandledPromiseRejectionWarning: CannotExecuteNotConnectedError: 
Cannot execute operation on "default" connection because connection is not yet established.
```
Any ideas?

## Environment

<pre><code>
Nest versions:
    "@nestjs/common": "^7.0.9",
    "@nestjs/core": "^7.0.3",
    "@nestjs/graphql": "^7.3.7",
    "@nestjs/platform-express": "^7.0.11",
    "@nestjs/typeorm": "^7.0.0",
 
For Tooling issues:
- Node version: v12.14.1
- Platform: Mac

Others:

</code></pre>

**Comment by ceopaludetto** [comment]
I figure out. Changing either tsconfig or babel.config fix the issue for me. You can just modify tsconfig module compiler options to CommonJS or @babel/preset-env module to cjs.

Note: Apply this modification only in server side, this will break your side effect free modules in client side(if you use).

Example:
babel.config.js or .babelrc
```javascript
module.exports = {
  presets: [
    ["@babel/preset-env", {
        modules: "cjs" // or isServer ? "cjs" : false
    }]
  ]
}
```
tsconfig.json
```json
{
  "compilerOptions": {
     "module": "CommonJS"
  }
}
```

Doens't apply the modification in both, choose one, if you choose tsconfig, set modules in babel to false, if you choose babel, set modules in tsconfig to ESNext(avoid double modification in your modules).

Verify too if your externals in webpack is setted.

Can you try @brandon-leapyear ?

**Comment by brandon-leapyear** [comment]
`tsconfig.json` already has `module` set to `commonjs`. We don't have a `babel.config.js` or `.babelrc` file; we're using the `nest` CLI

**Comment by brandon-leapyear** [comment]
https://github.com/brandon-leapyear/nest-graphql-typeorm-hmr

Minimal repro here. Running HMR currently gets the typeorm error:
```
AlreadyHasActiveConnectionError: Cannot create a new connection named "default", 
because connection with such name already exist and it now has an active connection 
session.
```
feel free to play around on there

**Comment by brandon-leapyear** [comment]
Never mind, got it working with `keepConnectionAlive`. The reason it wasn't working was because I was setting it to `process.env.NODE_ENV === 'development'`, but it turns out that `NODE_ENV` wasn't actually defined. Setting `keepConnectionAlive: !!module.hot` works
