### ISSUE TITLE
Add hint in testing docs mentioning Test.createTestingModule().compile() does not call lifecycle hooks

### ISSUE THREAD

**Issue by mattjbrent** [nestjs/docs.nestjs.com#1321]
its unclear in the docs (looked in both testing and lifecycle events) that lifecycle hooks are not automatically called when creating a testing module and calling the compile() method.

This can be remedied by adding a simple hint box in the testing section that mentions this fact, and also that the lifecycle methods can be called manually for testing purposes. 

This simple addition would save developers time as it seems reasonable to assume that most developers would assume the lifecycle hooks are called automatically in testing as they are at normal runtime.

Willing to add this in a PR myself.

**Comment by kamilmysliwiec** [comment]
PRs are more than welcome :)

**Comment by mattjbrent** [comment]
Sorry for not getting to this - I see this has been resolved by another contributor once merged.

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/docs.nestjs.com/pull/1618
