### ISSUE TITLE
ApiHeaders decorator does not work on class 

### ISSUE THREAD

**Issue by donprecious** [nestjs/docs.nestjs.com#1325]
Am trying to use 
@ApiHeaders([{name: "client-id", description: "client-id assigned to your app"]})
export class EmailController { 

 } 
it not working , i want to use @ApiHeaders because i have multiple headers i need to include, using just @ApiHeader would only accept 1 header  

i get this error 
error TS1238: Unable to resolve signature of class decorator when called as an 
expression.
  Type 'TypedPropertyDescriptor<unknown>' is not assignable to type 'void | typeof EmailController'.
    Property 'prototype' is missing in type 'TypedPropertyDescriptor<unknown>' but required in type 'typeof EmailController'.

**Comment by kamilmysliwiec** [comment]
Fixed in 4.5.12

**Comment by donprecious** [comment]
when you say fixed in 4.5.12, please can you explain i started using nest last week
