### ISSUE TITLE
Add type to the UploadedFile argument

### ISSUE THREAD

**Issue by incompletude** [nestjs/docs.nestjs.com#1326]
## Is your feature request related to a problem? Please describe.

Took me a while to find the proper type to a `file` from `@UploadedFile()` decorator.

## Describe the solution you'd like

Add the following to the docs:

`npm i -D @types/multer` 

```
  @Post()
  @UseInterceptors(FileInterceptor("file"))
  uploadFile(@UploadedFile() file: Express.Multer.File): void {
    console.log(file)
  }
```

**Comment by kamilmysliwiec** [comment]
PRs are more than welcome!

**Comment by incompletude** [comment]
I will send a PR. Thx.

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/docs.nestjs.com/pull/1604
