### ISSUE TITLE
createParamDecorator is only accepting string for data

### ISSUE THREAD

**Issue by ToonvanStrijp** [nestjs/docs.nestjs.com#138]
## I'm submitting a...
[ x ] Regression 
</code></pre>

## Current behavior

I'm using the 'createParamDecorator' but since the update it's only possible to pass string data

## Expected behavior

I want to pass in an object or array

## What is the motivation / use case for changing the behavior?
I'm using the decorator to add custom select fields to my database query.

## Environment

<pre><code>
For Tooling issues:
- Node version: v8.11.2
- Platform:  Max

**Comment by kamilmysliwiec** [comment]
Just fixed in latest patch update 5.2.2
