### ISSUE TITLE
Injecting multiple typeorm connections in a module provider via useFactory

### ISSUE THREAD

**Issue by justvamp** [nestjs/docs.nestjs.com#1442]
## I'm submitting a...
<pre><code>[v] Documentation request
</code></pre>

## Current behavior
Topic: https://docs.nestjs.com/techniques/database#multiple-databases
In order to inject a main connection in a module provider via `useFactory` we just have to use `inject: [Connection]`, whereas a way to inject a second (or bigger) connection is not covered.

## Expected behavior
There should be a reference to use `inject: [getConnectionToken('2nd-connection-name')]` or another solution.

## What is the motivation / use case for changing the behavior?
I took a while to realize how to do it. Googling also didn't help.

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this?

**Comment by justvamp** [comment]
> Would you like to create a PR for this?

Yeah, why not. Could you confirm that the solution is acceptable and `getConnectionToken` is not only intended to be used in the testing environment?

**Comment by kamilmysliwiec** [comment]
Yes, using `getConnectionToken` is completely fine.
