### ISSUE TITLE
[Kafka Microservice] Message/Event Deserialization Not In Line With Documentation

### ISSUE THREAD

**Issue by bradsheppard** [nestjs/docs.nestjs.com#1443]
## Bug Report
In the Kafka microservice documentation it states that:

> Nest receives incoming Kafka messages as an object with key, value, and headers properties that have values of type Buffer. Nest then parses these values by transforming the buffers into strings. If the string is "object like", Nest attempts to parse the string as JSON. The value is then passed to its associated handler.

However this doesn't appear to be the case. As an example, suppose we have a controller class with an event handler as follows:

```ts
@EventPattern('dog-created')
async handleDogCreated(@Payload() createDog: CreateDogDto): Promise<Dog> {
    return await this.dogService.create(createDog);
}
```
with the associated DTO:

```ts
export class CreateDogDto {
    name: string;
}
```

If we add a breakpoint at the return statement and inspect the value of `createDog` we will see an object of the following form:

```json
{
  "magicByte": 2,
  "attributes": 0,
  "timestamp": "1598110607591",
  "offset": "18",
  "key": null,
  "value": {
    "name": "Test Dog"
  },
  "headers": {},
  "isControlRecord": false,
  "batchContext": {
    "firstOffset": "18",
    "firstTimestamp": "1598110607591",
    "partitionLeaderEpoch": 0,
    "inTransaction": false,
    "isControlBatch": false,
    "lastOffsetDelta": 0,
    "producerId": "-1",
    "producerEpoch": 0,
    "firstSequence": 0,
    "maxTimestamp": "1598110607591",
    "magicByte": 2
  },
  "topic": "dog-created",
  "partition": 0
}
```

I believe this is because `server-kafka.ts` in the microservices package appears to use the default deserializer inherited from `server.ts` (i.e. `IncomingRequestDeserializer.ts`), when it should probably have its own custom deserializer (similar to `kafka-response.deserializer.ts` which `client-kafka.ts` uses). 

## Current behavior

Current event deserialization based on the above example:

```json
{
  "magicByte": 2,
  "attributes": 0,
  "timestamp": "1598110607591",
  "offset": "18",
  "key": null,
  "value": {
    "name": "Test Dog"
  },
  "headers": {},
  "isControlRecord": false,
  "batchContext": {
    "firstOffset": "18",
    "firstTimestamp": "1598110607591",
    "partitionLeaderEpoch": 0,
    "inTransaction": false,
    "isControlBatch": false,
    "lastOffsetDelta": 0,
    "producerId": "-1",
    "producerEpoch": 0,
    "firstSequence": 0,
    "maxTimestamp": "1598110607591",
    "magicByte": 2
  },
  "topic": "dog-created",
  "partition": 0
}
```

## Expected behavior

Expected event deserialization based on above example:

```json
{
  "name": "Test Dog"
}
```

## Possible Solution

One of:
- Create a custom deserializer to use with `server-kafka.ts` (which I'd be more than happy to do :smile:  )
- Update the documentation to more accurately reflect the behavior mentioned above.
## Environment

<pre><code>
Nest version: 7.4.2

 
For Tooling issues:
- Node version: 12.18.0  
- Platform: Linux  

Others:

</code></pre>

**Comment by bradsheppard** [comment]
@kamilmysliwiec Sure, I'll follow-up with a PR in the next few days.

**Comment by exilent-ashish** [comment]
@bradsheppard Have any solution you got?
