### ISSUE TITLE
Slow scrolling in the documentation

### ISSUE THREAD

**Issue by ryanmr-daugherty** [nestjs/docs.nestjs.com#15]
On my MacBook Pro, scrolling with the trackpad anywhere in the lefthand side table of contents tree is extremely jerky, while in the primary content area it is fluid.

It's likely related to a scroll or wheel event being fired too often.

**Comment by kamilmysliwiec** [comment]
Hi @ryanmr-daugherty,
It should be fixed already. Could you let me know?

**Comment by ryanmr-daugherty** [comment]
Thanks, looking good now!
