### ISSUE TITLE
synchronize warning in database docs

### ISSUE THREAD

**Issue by WillSquire** [nestjs/docs.nestjs.com#1528]
Noticed the [database docs](https://docs.nestjs.com/techniques/database) have `synchronize` listed as part of the configuration, but I don't see a warning that this can tank your production database. Might be a good idea to flag that up.

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by WillSquire** [comment]
Sure. I might mention doing something like:

```ts
...(process.env.NODE_ENV === 'development'
  ? { synchronize: true }
  : {}),
```

With `NODE_ENV=development` in `start:dev`. 

How does that sound?

**Comment by kamilmysliwiec** [comment]
Just adding a hint (blockquote) under the configuration that `synchronize` shouldn't be enabled in production would be sufficient.

**Comment by WillSquire** [comment]
https://github.com/nestjs/docs.nestjs.com/issues/1528

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/docs.nestjs.com/pull/1529
