### ISSUE TITLE
The "resource" schematic needs to be documented in the CLI section

### ISSUE THREAD

**Issue by smolinari** [nestjs/docs.nestjs.com#1551]
Hi,

The docs are currently missing the "resource" schematic. If I get the chance, I'll do a PR to correct it. 

Scott

**Comment by kamilmysliwiec** [comment]
There's a whole recipe on this feature https://docs.nestjs.com/recipes/crud-generator 

But still, we should probably mention that this schematic exists in the CLI section as well. PRs are more than welcome!
