### ISSUE TITLE
Do not mention TypeORM as the most mature TypeScript ORM

### ISSUE THREAD

**Issue by alpharder** [nestjs/docs.nestjs.com#1575]
Docs states:
```
Nest uses TypeORM because it's the most mature Object Relational Mapper (ORM) available for TypeScript. 
```

However, the TypeORM seems not to be maintained anymore as active as it should be for a project of that scale.
It has rare releases and too much bugs (1.4k issues at Github!).

I doubt whether it's a definition of "the most mature Object Relational Mapper (ORM) available for TypeScript" while there are other options available like MikroORM. It's younger but much more stable.

**Comment by kamilmysliwiec** [comment]
The number of issues isn't an indicator of whether a library/framework has bugs. Based on my experience maintaining the entire NestJS ecosystem for the last few years, I can assure you 95% of issues are: (1) the support questions (2) related to invalid usage of the library (misunderstanding) (3) issues within the developer codebases (not the library itself) and lastly (4) minor, unessential improvements.

Likewise, a library isn't "more stable" when it's actively developed & maintained. Some projects, at some point (typically after years of development), just become stable/"final". For instance, if you look at `express`, still the most popular library for creating APIs in Node, you'll notice that it wasn't updated in almost 2 years + over the past few years, all patch/minor releases contain only internal dependencies/docs updates.

**Comment by alpharder** [comment]
@kamilmysliwiec 

Overall, I agree with you that most issues don't require code changes. But I cannot agree that TypeORM is stable and "most mature". Most popular – yes, definitely. I'd suggest replacing "mature" with "popular" and that's it.

Well, `express` has solid backers - it's a member of OpenJS foundation, thus we have an option to expect its stability and solidity.

TypeORM, however, has never passed a point when it became a stable product like express did.

Even TypeORM authors are directly telling to community: we don't have enough time to maintain this.

It's not about stability, TypeORM is mostly unusable without monkeypatching when we talk about enterprise-grade projects.

Thank you for your efforts on Nest.js and thank you for your attention.
