### ISSUE TITLE
Log levels for the default logger are very unconventional and need careful clarification in the docs.

### ISSUE THREAD

**Issue by kswope** [nestjs/docs.nestjs.com#1613]
On this page

https://docs.nestjs.com/techniques/logger#using-the-logger-for-application-logging

Near the top
```
specify the log level of detail (e.g., display errors, warnings, debug information, etc.)
```

Later this is vaguely clarified
```
To enable specific logging levels, set the logger property to an array of strings specifying the log levels to display, as follows:
```

The problem is that conventionally "log levels" implies a *filtering* of the severity of level, not specifying different "channels".  I've never seen log levels that worked like this.

Why this matters.  

* First its very beginner unfriendly.  Nobody expects it to work like this.
* It doesn't make any sense, who would need to log ['debug', 'error'] while ignoring 'warn'?
* How many apps go into production that specify only "warn" and its expected that "error" is also logged, when it's just silently eaten instead?

**Comment by kamilmysliwiec** [comment]
I do agree that using "log levels" here may be misleading & confusing. We should use "channels" or "flags" or anything else that more appropriately describes the actual behavior. Would you like to create a PR to the docs?

**Comment by kamilmysliwiec** [comment]
This will be fixed in the next release.

**Comment by ImJoeHs** [comment]
@kamilmysliwiec sry for disturbing, could nestjs provide a new option `logLevel` and mark `logLevels` deprecated?

Now we still set the level option as an array
![image](https://user-images.githubusercontent.com/13445155/129439781-dcae8963-6f42-482c-b498-27ff2c4857cc.png)

As for me, it's quite confusing until i dig into source and finnaly realize that these two options (`['warn']` & `['warn', 'error']`) work exactly the same

**Comment by kamilmysliwiec** [comment]
This is explained in the docs.

There are no plans to change the current behavior atm.
