### ISSUE TITLE
Improve Swagger Plugin Docs

### ISSUE THREAD

**Issue by woody34** [nestjs/docs.nestjs.com#1622]
## Is your feature request related to a problem? Please describe.

I tried out some new node frameworks to spin up basic services, one of which was nest! I attempted to use your swagger plugin. The documentation was lacking and I ended up going to look at the tests to figure out which decorators I needed to use to get the API working with swagger. It would be nice to improve those docs. 

## Describe the solution you'd like

Better documentation on your plugins. The core framework docs seem to be good.

## Teachability, Documentation, Adoption, Migration Strategy

Better plugin docs will improve adoption in my humble opinion. Of the new frameworks I tried I did not chose to use nest further because I had to spend more time setting up a basic API. I had a conversation with a peer that recommended nest and confirmed he also had to look at tests to better understand how some things worked. I ended really liking [tsed](https://tsed.io) for how fast I got up and running. It scaffolds everything I needed for my basic service, including options for docker which I found really nice. I ran the CLI to init my project, made some small changes, added my routes and off I went. I realize both frameworks are targeting different audiences but I hope you find this feedback valuable.

## What is the motivation / use case for changing the behavior?

I would like to shorten the learning curve / adopt the framework more quickly.

**Comment by woody34** [comment]
[Project](https://github.com/woody34/micro-code)

# Decorators Used With No Docs
I had to look at your tests to derive how and what I should decorate to get swagger working properly. It seemed I had to duplicate my schema options in the property decorator? I didn't spend too much time on it as I was testing different frameworks and the docs didn't explain it well, hence the reason for the feedback. The docs did explain how to get swagger setup very well!

controller:
```
  @ApiOkResponse({ type: [Code] })
  @ApiBody({ type: Code })
  @ApiCreatedResponse({ type: Code })
  @ApiOperation({ summary: 'Delete code doc by Id' })
  @ApiParam({ name: 'id', type: 'string' })
  @ApiNoContentResponse()
```

schema:
```
  @ApiProperty({ minimum: 0, maximum: 75, required: true })
```

Take the feedback as you will, you're welcome to close the issue with no action I just figured it may bring you value. Thank you for your time!

**Comment by Tony133** [comment]
What would be the missing parts to add?
