### ISSUE TITLE
Add Documentation About bull-board

### ISSUE THREAD

**Issue by henriqueleite42** [nestjs/docs.nestjs.com#1688]
## I'm submitting a...

- [x] Documentation issue or request

## What is the motivation / use case for changing the behavior?

Hello guys, first of all, thanks for the awesome framework, it helps a lot! :smile: 

Now, about this issue, I'm missing documentation about how to integrate the bull-board, mainly using controllers with guards.

I created an issue in the [@nestjs/bull](https://github.com/nestjs/bull) repo, and the guys suggested creating the issue here since this is the documentary repo.

If anyone has any free time, can you add this documentation here? I think it would be of great help to the community since the bull-board is used a lot.

Thanks again! :smile:

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/bull/issues/675#issuecomment-766615168
