### ISSUE TITLE
Missing quotes on Mongoose (Techniques -> Mongo) Testing instructions

### ISSUE THREAD

**Issue by FredericoGauz** [nestjs/docs.nestjs.com#1763]
In this part of the page:

`@Module({
  providers: [
    CatsService,
    {
      provide: getModelToken(Cat.name),
      useValue: catModel,
    },
  ],
})
export class CatsModule {}`

**`useValue: catModel`**

Is missing "" (quotes)

Should be: `useValue: "catModel"`

**Comment by jmcdo29** [comment]
This isn't a bug. `catModel` is assumed to be a variable that _looks_ like the mongoose cat model, so that you can override the actual injected value. It's a [Custom Provider](https://docs.nestjs.com/fundamentals/custom-providers)
