### ISSUE TITLE
Routing section 

### ISSUE THREAD

**Issue by abelardolg** [nestjs/docs.nestjs.com#1798]
Hi there,

I would like to suggest you an improvement.

At the "Getting started" section, you explain routing mixed with controllers. But is a best practice to separate routing paths from controllers. Anyway, I think it's a best option to create an isolated section dedicated to routing (if possible, before the controller section).

❓ By using NestJS, could we create separated files to store our routes instead of mixing them inside our controllers?

Best regards.

**Comment by kamilmysliwiec** [comment]
> At the "Getting started" section, you explain routing mixed with controllers. But is a best practice to separate routing paths from controllers.

It depends on what you prefer. I'd not call it a best practice and so there's no such recommendation in the docs.
