### ISSUE TITLE
Webpack and `typeorm` CLI

### ISSUE THREAD

**Issue by avidan-chen** [nestjs/docs.nestjs.com#1848]
Webpack bundles your code to a single executable JavaScript file. Hence, if you want to use `typeorm` CLI to run compiled migration files (using a blob path), you should rather build them separately using `tsc`

_Originally posted by @kamilmysliwiec in https://github.com/nestjs/nest/issues/3223#issuecomment-545830198_

**Comment by avidan-chen** [comment]
Can this be added to the docs along with a detailed explanation on how to use tsc for working with `typeorm` CLI and switch for webpack for bundling? I understand that for monorepos the recommended approach is to set "webpack": "true" in `nest-cli.json`, but it's unclear why that is the case (not explained at all in the docs), and it's also unclear what's the correct flow to work with `typeorm` CLI in that scenario.

**Comment by kamilmysliwiec** [comment]
> Can this be added to the docs along with a detailed explanation on how to use tsc for working with typeorm CLI

This is explained in the `typeorm` documentation. Please, keep in mind that `typeorm` is a separate project, not a part of the NestJS organization.

> I understand that for monorepos the recommended approach is to set "webpack": "true" in nest-cli.json, but it's unclear why that is the case (not explained at all in the docs)

Without webpack, the directories structure inside the `dist` folder would be a mess.

>  and it's also unclear what's the correct flow to work with typeorm CLI in that scenario.

This isn't related to NestJS. TypeORM CLI shouldn't be bundled along with the application, nor the migration files.

**Comment by avidan-chen** [comment]
All I'm saying is that by using webpack (and sorry, I still don't understand what do you mean by "the directories sturcture... would be a mess"), I get a single file instead of the same folder structure I have when I use tsc, and by having just a single file, It's impossible to use the `typeorm` CLI (because it can't find the entitites).

So I would think that an explanation on the correct (or "proper") flow of working in NestJS along with Typeorm when using the monorepo mode is something a lot of people would be intersted in. For me, I can say that I when I created the monorepo I spent a lot of time trying to understand why typeorm CLI wouldn't work with it, and while typeorm is a separate project, an overview of best practices of using it in tandem with monorepo mode might be important to others as well. 

For example, to run typeorm CLI commands, do I go to nest-cli.json and set "webpack" to false, build, run the typeorm commands, and switches back "webpack" to true? Is that the recommended approach by the team behind NestJS?

**Comment by kamilmysliwiec** [comment]
> For example, to run typeorm CLI commands, do I go to nest-cli.json and set "webpack" to false, build, run the typeorm commands, and switches back "webpack" to true? Is that the recommended approach by the team behind NestJS?

To run typeorm CLI commands, you should never use `nest build` as there's simply no reason to bundle your migration files, and so any changes to the `nest-cli.json` file are not required. You should have a separate build step using `tsc` or alternatively, you could use `ts-node` as **shown in the typeorm docs**.

> All I'm saying is that by using webpack (and sorry, I still don't understand what do you mean by "the directories sturcture... would be a mess"), I get a single file instead of the same folder structure I have when I use tsc, and by having just a single file, It's impossible to use the typeorm CLI (because it can't find the entities).

That's what I've said above^ "TypeORM CLI shouldn't be bundled along with the application, nor the migration files."

> So I would think that an explanation on the correct (or "proper") flow of working in NestJS along with Typeorm when using the monorepo mode is something a lot of people would be intersted in. For me, I can say that I when I created the monorepo I spent a lot of time trying to understand why typeorm CLI wouldn't work with it, and while typeorm is a separate project, an overview of best practices of using it in tandem with monorepo mode might be important to others as well.

The contributions to the documentation are more than welcome. As this doesn't seem to be crucial to me (which doesn't necessarily mean it's not valuable at all!), we're not tracking this & nor planning to add it in the foreseeable future. However, if there's any PR containing some additional tips & hints, we'll definitely consider merging it!
