### ISSUE TITLE
The Cookies page in the docs is broken

### ISSUE THREAD

**Issue by ivorpad** [nestjs/docs.nestjs.com#1860]
https://docs.nestjs.com/techniques/cookies

**Comment by Tony133** [comment]
I think it is because of Netlify as they have some problems see here: https://www.netlifystatus.com/

**Comment by avidianity** [comment]
I can't open the whole website. Did something happen?

**Comment by Tony133** [comment]
the NestJS site uses Netlify's cloud servers and at the moment Netlify seems to have problems so it's not Nest's problem.

**Comment by ivorpad** [comment]
I cloned the docs and ran it locally and the Cookies docs are still missing.

**Comment by jmcdo29** [comment]
[The component still exists in the router.](https://github.com/nestjs/docs.nestjs.com/blob/master/src/app/homepage/pages/techniques/techniques.module.ts#L93) I'll take a look later and see if its there locally for me

**Comment by Tony133** [comment]
@ivorpad I can see the cookie page (see screenshot)

<img width="1291" alt="screenshot" src="https://user-images.githubusercontent.com/11542387/112532597-4ca80000-8da9-11eb-89fb-b0b580c31946.png">

**Comment by Tony133** [comment]
also locally I can see the page
 
<img width="1292" alt="screenshot" src="https://user-images.githubusercontent.com/11542387/112534077-f471fd80-8daa-11eb-9b3b-ff4842ff19d9.png">

**Comment by ivorpad** [comment]
Ok, I can see it now. That was weird.
