### ISSUE TITLE
Documentation example code contains XSS vulnerability

### ISSUE THREAD

**Issue by asgerf** [nestjs/docs.nestjs.com#1899]
## Bug Report

The [controllers](https://docs.nestjs.com/controllers) documentation page contains the following two snippets:
```ts
@Get(':id')
findOne(@Param() params): string {
  console.log(params.id);
  return `This action returns a #${params.id} cat`;
}

@Get(':id')
findOne(@Param('id') id: string): string {
  return `This action returns a #${id} cat`;
}
```
Both contain a reflected XSS vulnerability, as a URL like
```
http://localhost:3000/%3Cimg%20src=x%20onerror=alert(1)%3E
```
causes JS code execution, since `params.id` gets the value `<img src=x onerror=alert(1)>` and the result is interpreted as HTML.

Note that this only affects the Express backend; with Fastify the content-type is not HTML when a string is returned from a route handler.

## Possible Solution
Some ideas:
- Rephrase the documentation to avoid showing examples with XSS.
- Warn of the security implications of returning untrusted string data from a route handler.
- It would be a breaking change, but just putting it out there anyway: make the Express backend align with Fastify and default to non-HTML content-type when a route handler returns a string. (I'm not familiar enough with the internals of Nest to determine if this is actually possible)

## Environment

<pre><code>
Nest version: 7.6.15
Express version: 4.17.1
</code></pre>

**Comment by kamilmysliwiec** [comment]
The examples we present in the "Controllers" chapter in the docs are meant to be very simple & straightforward and easy to understand. Strings we return from method handlers describe what the endpoints are supposed to do in a real-world application. However, a real-world application itself should never really return such strings, and this seems to be pretty obvious(?). If we went this route, we would also have to add the authentication logic to the "Post/Put/Delete" endpoints as they shouldn't be public (and they are public in the docs rn so we should flag them as "dangerous").

If anyone is interested in creating a PR with a warning on XSS (just in case? or just a warning that "returned values act as placeholders in these examples"), a small blockquote, we _may consider_ to merge it, but there's no plan to update the actual examples.
