### ISSUE TITLE
Remove support reference from support page.

### ISSUE THREAD

**Issue by ph55** [nestjs/docs.nestjs.com#197]
Go to https://docs.nestjs.com/support
There is a support block at the bottom that links to itself.

![image](https://user-images.githubusercontent.com/1386622/48448697-8499e400-e7a8-11e8-930f-c894bcc6ccc1.png)

**Comment by kamilmysliwiec** [comment]
It's a part of the page footer (that is why it appears on every page).

**Comment by lazarljubenovic** [comment]
I think OP's idea was to treat it as an exception and remove it since it just repeats the page intent again.
