### ISSUE TITLE
Using Webpack build in v8 logs [HMR] Nothing hot updated. continuously

### ISSUE THREAD

**Issue by Hwan-seok** [nestjs/docs.nestjs.com#1978]
## Current behavior
After upgrading to v8, the project built by webpack(for using hmr) is showing weird behavior.
The log `[HMR] Nothing hot updated.` is continuously showing even if I didn't modify codes after the application started.

```
[Nest] 18296  - 2021. 07. 26. 오후 3:22:29     LOG [NestFactory] Starting Nest application... +207ms
[Nest] 18296  - 2021. 07. 26. 오후 3:22:29     LOG [InstanceLoader] AppModule dependencies initialized +153ms
[HMR] Nothing hot updated.
[HMR] Nothing hot updated.
[HMR] Nothing hot updated.
[HMR] Nothing hot updated.
[HMR] Nothing hot updated.
....
...
[HMR] Nothing hot updated.  // (indefinitely....)
```

## How To Reproduce

> mkdir repro-app && cd repro-app
> npm install @nestjs/cli@8
> npx nest n .
> copy & paste webpack.config.js  from [docs](https://docs.nestjs.com/recipes/hot-reload#configuration-1)
> npm install -D webpack webpack-cli webpack-node-externals
> npx webpack

## Environment

<pre><code>
Nest version: 8.0.0

 
For Tooling issues:
- Node version: v14.15.1
- Platform:  windows

Others:

</code></pre>

**Comment by Hwan-seok** [comment]
Hmm... even if I removed all plugins except HMR plugin, the same is occurs

**Comment by kamilmysliwiec** [comment]
You're right, thanks @Hwan-seok! Let me look into it again

**Comment by Tony133** [comment]
This problem has been fixed with the new version of `@nestjs/cli`, release: `8.1.1`.

**Comment by Hwan-seok** [comment]
@Tony133 

What commit or PR is related to this?

**Comment by Tony133** [comment]
@Hwan-seok  take a look here (see also screenshot): https://github.com/nestjs/nest-cli/releases/tag/8.1.1

<img width="952" alt="screenshot" src="https://user-images.githubusercontent.com/11542387/128026334-629c74f1-e083-4c3a-b729-ed99de918739.png">

Try to update the nest cli(`npm install -g @nestjs/cli`) and you should fix it, I did it and it worked.
