### ISSUE TITLE
Update setup options (swagger) for fastify-based apps

### ISSUE THREAD

**Issue by pktai** [nestjs/docs.nestjs.com#1982]
hi everyone, I am using swagger in combination with `nestjs fastify`, but in options setup swagger, `urls` property is not working. please help me.

![image](https://user-images.githubusercontent.com/36804773/127320855-3fd29504-74b2-40cf-96ec-d8a129ed7997.png)

**Comment by kamilmysliwiec** [comment]
Fastify users should use a different options object, see source https://github.com/nestjs/swagger/blob/833458d371d929d14ed5d9b8c32f51429e56dd28/lib/interfaces/swagger-custom-options.interface.ts#L15

We should update the docs to reflect that change

**Comment by Tony133** [comment]
I would say that this problem can be closed 😉👍
