### ISSUE TITLE
Incorrect link in the Authentication Docs page

### ISSUE THREAD

**Issue by mateusgrb** [nestjs/docs.nestjs.com#1998]
## Current behavior
There seems to be an incorrect links in the Authentication Docs page. Look for this part: "Other options, such as a PEM-encoded public key, may be more appropriate for production apps (see here for more information)". The link in the word `here` takes to a jwt extraction page, the same link referred 4 lines above.

## Expected behavior
It should take me to a page related to more appropriate keys/secrets for a production app.

## Possible Solution
Update link.

**Comment by mateusgrb** [comment]
sorry @Tony133 missed your previous messages. Thanks for fixing this.

**Comment by Tony133** [comment]
No problem, thanks to you for reporting  😉👍
