### ISSUE TITLE
Optional request scoped dependencies break lifecycle hooks

### ISSUE THREAD

**Issue by zaslavskyv** [nestjs/docs.nestjs.com#2031]
## Current behavior
Lifecycle hooks that _optionally_ depend on request scoped providers are not executed.

## Input Code
https://github.com/zaslavskyv/nestjs-optional-request

```ts
import { Injectable, Inject, Optional, OnApplicationBootstrap } from "@nestjs/common";
import { REQUEST } from "@nestjs/core";

@Injectable()
export class StartService implements OnApplicationBootstrap {
  // the hook will not be executed if the next line is uncommented
  // constructor(@Optional() @Inject(REQUEST) request: any) {}

  onApplicationBootstrap(): void {
    console.log("Bootstrapped!");
  }
}
```

## Expected behavior
`undefined` is passed to the constructor and the hook is executed.

## Environment
<pre><code>Nest version: 8.0.6</code></pre>

**Comment by kamilmysliwiec** [comment]
Regardless of whether the request-scoped dependency is optional or not, the provider will implicitly become request-scoped and this is an intended behavior. Let me move this to the docs repository and update the Scopes chapter asap

**Comment by zaslavskyv** [comment]
Please consider at least a console warning then.

**Comment by kamilmysliwiec** [comment]
Let's keep this open so we can track the required docs update

**Comment by micalevisk** [comment]
I guess this can be closed

![image](https://user-images.githubusercontent.com/13461315/163004756-08e498e4-8fc5-4336-a367-e036184fc711.png)


https://github.com/nestjs/docs.nestjs.com/blob/5712aaa8871711ca2d100e8d4afb74f528d5761a/content/fundamentals/lifecycle-events.md?plain=1#L27
