### ISSUE TITLE
Documentation for implementing forRootAsync

### ISSUE THREAD

**Issue by optimistex** [nestjs/docs.nestjs.com#2136]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

From the documentation is not clear yet how to implement `forRootAsync` method.

I've checked in this places:
- https://docs.nestjs.com/modules
- https://docs.nestjs.com/fundamentals/dynamic-modules

### Describe the solution you'd like

After research and reading source code here https://github.com/nestjs/graphql/blob/master/lib/graphql.module.ts I've end up with pretty simple solution that **would be good to have in the official documentation**.

```typescript
export const HTTP_NOTIFICATION_MODULE_OPTIONS = 'HTTP_NOTIFICATION_MODULE_OPTIONS';

export interface HttpNotificationModuleOptions {
  legalDocumentPublishChangesUrl: string;
}

export type ModuleAsyncOptions<Options> = Pick<FactoryProvider<Options>, 'inject' | 'useFactory'>;

@Module({})
export class HttpNotificationModule {
  public static forRootAsync(options: ModuleAsyncOptions<HttpNotificationModuleOptions>): DynamicModule {
    return {
      module: HttpNotificationModule,
      providers: [
        { provide: HTTP_NOTIFICATION_MODULE_OPTIONS, ...options },
        HttpNotificationService,
      ],
      exports: [HttpNotificationService],
    };
  }
}

@Module({
  imports: [
    // ...
    HttpNotificationModule.forRootAsync({ inject: [ConfigService], useFactory: (config: ConfigService) => config.env.httpNotificationConfig }),
  ],
  controllers: [
    // ...
  ],
})
export class ApiRestModule {
}
```

### Teachability, documentation, adoption, migration strategy

Users can read the documentation and save their time.

### What is the motivation / use case for changing the behavior?

Just save the time on research.

**Comment by mohsinamjad** [comment]
if it works, then it should be included in official docs under the section of the dynamic module.

**Comment by kamilmysliwiec** [comment]
https://docs.nestjs.com/fundamentals/dynamic-modules#configurable-module-builder
