### ISSUE TITLE
There is no information on how to write e2e tests for a microservice to doc(p.s. i use nats)

### ISSUE THREAD

**Issue by BaurinVladislav** [nestjs/docs.nestjs.com#2274]
Good afternoon!

I apologize in advance for the bad English (Google translator).
I started studying backend development in js using the Nest JS framework. Previously I used Java Spring Boot for development.

There is no information on how to write e2e tests for microservices on the official NestJS website and on github (p.s. I use the NATS broker). I have already spent 3 days to figure it out, but failed.

**Where can I get a guide for writing an e2e test for a microservice?**

Sincerely, Vladislav.

**Comment by BaurinVladislav** [comment]
Or perhaps you could provide an example for research. I will be very grateful.

**Comment by jmcdo29** [comment]
This repo has some generalized testing samples: https://GitHub.com/jmcdo29/testing-nestjs

Otherwise your general idea would be something like this:
```
Spin up the broker
Spin up the server
Spin up the client
Make request to client
Assert the client's response
Close client
Close server
Close broker
```

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
