### ISSUE TITLE
replacing documentation with Vue 3

### ISSUE THREAD

**Issue by productdevbook** [nestjs/docs.nestjs.com#2339]
Hello,

As someone who ate the vue and vite ecosystem, I want to migrate all the nestjs documentation to Vue 3. It will also be more beautiful and accessible and legible.

If i am create a pr and work, would that be welcomed?

Thank you,

**Comment by Tony133** [comment]
See this issues/discussion https://github.com/nestjs/docs.nestjs.com/issues/2240.

However, I think it doesn't make much sense at the moment, and a huge overhead for the core nest team. The documentation (the Angular app) is manageable and works quite well at the moment. (My opinion)
