### ISSUE TITLE
How to use @nestjs/bullmq. No documentation for it!

### ISSUE THREAD

**Issue by snawaz** [nestjs/docs.nestjs.com#2353]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

`@nest/bullmq` has been added and I'm trying to migrate from `(@nestjs/bull, bull)` to `(@nestjs/bullmq,  bullmq)`. But I don't see any docs explaining how to use it. There are definitely some differences between these two. The docs at https://docs.nestjs.com/techniques/queues explains things as per ` @nest/bull`. 

### Describe the solution you'd like

Please add some documentation and I think the link https://docs.nestjs.com/techniques/queues should be removed from README of `@nestjs/bullmq`. 

### Teachability, documentation, adoption, migration strategy

If the relevant docs are added, the users would be able to use bullmq.

### What is the motivation / use case for changing the behavior?

Migrating to `bullmq` which is newer and probably better!

**Comment by aradwann** [comment]
I found this on bullmq side which might be helpful, 
https://docs.bullmq.io/bullmq-pro/nestjs

**Comment by IlCallo** [comment]
I guess most of the people isn't going to use the bullmq pro version, so the following link could be more useful
https://docs.bullmq.io/guide/nestjs

**Comment by saratscheff** [comment]
@kamilmysliwiec would it be helpful if I open a PR updating the documentation to show steps for BullMQ instead of Bull?

**Comment by njgerner** [comment]
I also created an example repo outlining usage https://github.com/njgerner/nestjs-bullmq-example

Nick

**Comment by kamilmysliwiec** [comment]
@saratscheff ideally we should showcase both

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/docs.nestjs.com/pull/2805
