### ISSUE TITLE
Why AccessTokenStrategy (@UseGuards(AuthGuard('jwt'))) always returns Unauthorized 401?

### ISSUE THREAD

**Issue by TanyaDovzhenko** [nestjs/docs.nestjs.com#2378]
I'm really bad in jwt and can't understand why i always have "unauthorized" when i'm trying to logout. Others endpoints in my auth api works in a right way, i can sign up and sign in, but when a try to logout i always have "unauthorized". I'm testing this in Postman, where I pass the authorization field and Bearer to the headers

Auth Controller: 

`@Controller('auth')
export class AuthController {
    constructor(private authService: AuthService) { }

    @Post('signup')
    signup(@Body() createUserDto: CreateUserInput): Promise<Tokens> {
        return this.authService.signup(createUserDto)
    }

    @Post('signin')
    signin(@Body() signInDto: SignInDto): Promise<Tokens> {
        return this.authService.signin(signInDto)
    }

    @Post('logout')
    @UseGuards(AuthGuard('jwt'))
    logout(@Req() req: Request) {
        const user = req.user
        return this.authService.logout(user['sub'])
    }
}`

-----------------------------------------------------------------------
Auth Service:

`@Injectable()
export class AuthService {
    constructor(private userService: UserService,
        private jwtService: JwtService) { }

    async signup(createUserDto: CreateUserInput): Promise<Tokens> {
        const hashedPassword = bcrypt.hashSync(createUserDto.password, 3)
        const user = await this.userService.createUser({ ...createUserDto, password: hashedPassword })
        const tokens = await this.getTokens(user.id, user.email)
        await this.userService.updateRefreshTokenHash(user.id, tokens.refresh_token)
        return tokens
    }

    async signin(signInDto: SignInDto): Promise<Tokens> {
        const user = await this.userService.findOneByEmail(signInDto.email)
        const passwordValid = bcrypt.compareSync(signInDto.password, user?.password)
        if (!user || !passwordValid) throw new UnauthorizedException()

        const tokens = await this.getTokens(user.id, user.email)
        await this.userService.updateRefreshTokenHash(user.id, tokens.refresh_token)
        return tokens
    }

    async logout(userId: number) {
        return await this.userService.updateRefreshTokenHash(userId, null)
    }

    async getTokens(userId: number, email: string): Promise<Tokens> {
        const [access_token, refresh_token] = await Promise.all([
            this.jwtService.signAsync(
                { sub: userId, email }, { secret: 'rt111', expiresIn: 60 * 15 }),
            this.jwtService.signAsync(
                { sub: userId, email }, { secret: 'at111', expiresIn: 60 * 60 * 24 * 7 })
        ])
        return { access_token, refresh_token }
    }
}`

-----------------------------------------------------------------------

How i update refresh token in user service:

` async updateRefreshTokenHash(userId: number, refreshToken: string | null) {
    console.log(1234)
    const hash = bcrypt.hashSync(refreshToken, 3)
    return await this.userRepo.update({ hashedRefreshToken: hash }, { where: { id: userId } })
  }`

------------------------------------------------------------------------

And tokes stategies: 

`type JwtPayload = { sub: string, email: string }

@Injectable()
export class AccessTokenStrategy extends PassportStrategy(Strategy, 'jwt') {
    constructor() {
        super({
            jwtFromRequest: ExtractJwt.fromAuthHeaderAsBearerToken(),
            ignoreExpiration: false,
            secretOrKey: 'at111'
        })
    }

    validate(payload: JwtPayload) { return payload }
}`

`
@Injectable()
export class RefreshTokenStrategy extends PassportStrategy(Strategy, 'jwt-refresh') {
    constructor() {
        super({
            jwtFromRequest: ExtractJwt.fromAuthHeaderAsBearerToken(),
            ignoreExpiration: false,
            secretOrKey: 'rt111',
            passReqToCallback: true
        })
    }

    validate(req: Request, payload: any) {
        const refreshToken = req.get('authorization').replace('Bearer', '').trim();
        return { ...payload, refreshToken }
    }
}`

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
