### ISSUE TITLE
[document] mongodb ”Multiple databases“ do not work

### ISSUE THREAD

**Issue by GongT** [nestjs/docs.nestjs.com#2384]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

```
Nest can't resolve dependencies of the AppService (?). Please make sure that the argument testModel at index [0] is available in the AppModule context.
```

### Minimum reproduction code

https://github.com/GongT/issues/tree/nest-mongodb-multiple

### Steps to reproduce

1. run a mongodb (I use docker: `docker run -it --rm --name mongodb -p 27017:27017 mongo`)
2. npm install
3. npm run start

### Expected behavior

It should work

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### NestJS version

8.4.7

### Packages versions

```
[System Information]
OS Version     : Linux 5.18
NodeJS Version : v18.3.0
PNPM Version    : 7.2.1 

[Nest CLI]
Nest CLI Version : 8.2.8 

[Nest Platform Information]
platform-express version : 8.4.7
schematics version       : 8.0.11
mongoose version         : 9.1.1
testing version          : 8.4.7
common version           : 8.4.7
core version             : 8.4.7
cli version              : 8.2.8
```

### Node.js version

18.3.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

I'm following the document ([here](https://docs.nestjs.com/techniques/mongodb))

https://github.com/GongT/issues/blob/nest-mongodb-multiple/src/app.module.ts#L7-L20

**Comment by Tony133** [comment]
This issue we can close, it has been corrected through this PR: https://github.com/nestjs/docs.nestjs.com/pull/2434
