### ISSUE TITLE
Minor improvement for the website: use relative paths instead of absolute on hyperlinks to another page 

### ISSUE THREAD

**Issue by micalevisk** [nestjs/docs.nestjs.com#2404]
There are several pages with hyperlinks to another page of the docs like this:

https://github.com/nestjs/docs.nestjs.com/blob/d15ab28fe673d7d3cc4e6ebfb3cbf053556f7f90/content/techniques/caching.md?plain=1#L97

but using `https://docs.nestjs.com/` instead of `../../` isn't good for those looking at the docs of another version (like v8) because they'll be redirect to the docs of the active version instead:

https://user-images.githubusercontent.com/13461315/179424127-1f16c63f-eaf0-4c5a-8357-ccd81e71234a.mp4

---

[Here is all ocurrences](https://cs.github.com/nestjs/docs.nestjs.com?q=%22https%3A%2F%2Fdocs.nestjs.com%2F%22+path%3Acontent) of `https://docs.nestjs.com/` under `content` directory:

![image](https://user-images.githubusercontent.com/13461315/179424063-77731761-0830-444e-be9a-d0f588ec23d5.png)

changing them will be easy but there are a lot of files to manually touch.

I'm working on this issue already (slowly).

**Comment by Tony133** [comment]
We can follow this issue here https://github.com/nestjs/docs.nestjs.com/pull/2425 so we can close this issue, right?
