### ISSUE TITLE
nestjs.com can’t be reached

### ISSUE THREAD

**Issue by mehdikhody** [nestjs/docs.nestjs.com#2411]
<img width="621" alt="nestjs-website" src="https://user-images.githubusercontent.com/22590626/180067842-538b744c-f348-4ef5-a9f3-1fab0913f99b.png">

Hi, why I can't visit nestjs website ?

**Comment by Tony133** [comment]
it works for me (see screenshot)

<img width="1258" alt="screenshot-site" src="https://user-images.githubusercontent.com/11542387/180074847-11d0bc59-e859-45f6-833a-f9457ccaddd4.png">

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
