### ISSUE TITLE
Hot reload is generating errors after following online documentation from base installation exactly.

### ISSUE THREAD

**Issue by laurencefass** [nestjs/docs.nestjs.com#2422]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I am just using Nest.js for the first time and I have installed a basic Hello World following installation instructions here:

https://docs.nestjs.com/recipes/hot-reload

I selected yarn to install.

This recipe does not result in the exact same code as here though it is linked from the online docs:

https://github.com/nestjs/nest/tree/master/sample/08-webpack

Actual Result:

When I follow ALL the instructions to the letter I am seeing errors in the output that were not present before I following the Hot reload recipe so the extra steps have definitely introduced them. As far as I understand Typescript modules these errors do not make sense and were certainly not errors before I introduced hot reloading code.

```
16|nest-nest1  | ERROR in ./src/app.controller.ts:2:28
16|nest-nest1  | TS2306: File '/app/nest/nest1/src/app.service.ts' is not a module.
16|nest-nest1  |     1 | import { Controller, Get } from '@nestjs/common';
16|nest-nest1  |   > 2 | import { AppService } from './app.service';
16|nest-nest1  |       |                            ^^^^^^^^^^^^^^^
16|nest-nest1  |     3 |
16|nest-nest1  |     4 | @Controller()
16|nest-nest1  |     5 | export class AppController {
16|nest-nest1  | ERROR in ./src/app.module.ts:3:28
16|nest-nest1  | TS2306: File '/app/nest/nest1/src/app.service.ts' is not a module.
16|nest-nest1  |     1 | import { Module } from '@nestjs/common';
16|nest-nest1  |     2 | import { AppController } from './app.controller';
16|nest-nest1  |   > 3 | import { AppService } from './app.service';
```

### Minimum reproduction code

https://github.com/laurencefass/nest_hot_reload.git

### Steps to reproduce

1. clone the repo
2. yarn install
3. run, make code changes and observe output

### Expected behavior

1. The sample code and documentation should match, but there are slight variations.
2. The hot reload should work without errors.

### Package

- [X] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.0.0

### Packages versions

```bash-5.1# cat package.json
{
  "name": "nest1",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "prebuild": "rimraf dist",
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest build --webpack --webpackPath webpack-hmr.config.js --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/common": "^9.0.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/platform-express": "^9.0.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "run-script-webpack-plugin": "^0.1.1",
    "rxjs": "^7.2.0",
    "webpack": "^5.74.0",
    "webpack-node-externals": "^3.0.0"
  },
  "devDependencies": {
    "@nestjs/cli": "^9.0.0",
    "@nestjs/schematics": "^9.0.0",
    "@nestjs/testing": "^9.0.0",
    "@types/express": "^4.17.13",
    "@types/jest": "28.1.4",
    "@types/node": "^16.0.0",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "eslint": "^8.0.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "28.1.2",
    "prettier": "^2.3.2",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.3",
    "ts-jest": "28.0.5",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "4.0.0",
    "typescript": "^4.3.5"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}

```

### Node.js version

16.31.1

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by micalevisk** [comment]
```bash
git clone --depth=1 https://github.com/laurencefass/nest_hot_reload
cd nest_hot_reload
yarn install
yarn start:dev
# change couple files under src dir
```

I got no errors here :thinking:
