### ISSUE TITLE
How to exit REPL?

### ISSUE THREAD

**Issue by qortex** [nestjs/docs.nestjs.com#2423]
So nice to have REPL in v9!

I use Ctrl+C to exit REPL.

Is it the correct way?

I would expect Ctrl+C to just ignore current command. And then exit if repeated.

Wondering if there is another way (tried `.exit` & co)

**Comment by micalevisk** [comment]
as that REPL is just the same as the [nodejs REPL](https://nodejs.org/api/repl.html), <kbd>ctrl</kbd>+<kbd>c</kbd> and `.exit` should kill the app.

Feel free to open an issue at https://github.com/nestjs/nest if you have some app that doesn't exit on that manner.

I notice that it doesn't work that well when we use the watch mode (maybe it's related with https://github.com/nestjs/nest-cli/issues/1487)

https://user-images.githubusercontent.com/13461315/181935321-bf764780-3f4c-4123-9de7-07aadb938893.mp4

**Comment by Tony133** [comment]
I confirm that in watch mode the `.exit` does not work. (see screenshot)

<img width="1471" alt="screnshot" src="https://user-images.githubusercontent.com/11542387/182019891-c04c15c9-7d0d-4a17-bedd-7259221ed64c.png">

**Comment by qortex** [comment]
Ok, then `.exit` and Ctrl+C do not work as expected, I don't think I use watch mode.
I am in an Nx environment so maybe it is related?
Will investigate and open an issue if I understand more on the issue.

Leaving this open if more bug reports flow in.

**Comment by Tony133** [comment]
Without the watch mode the `.exit` and `CTRL + D` works perfectly, also the `CTRL + C` it is used for abort current expression, not to exit REPL.

<img width="1592" alt="screenshot" src="https://user-images.githubusercontent.com/11542387/182032227-b81d10a8-79da-412e-a3dc-609ad9b9b617.png">

**Comment by jmcdo29** [comment]
> Ok, then `.exit` and Ctrl+C do not work as expected, I don't think I use watch mode. I am in an Nx environment so maybe it is related? Will investigate and open an issue if I understand more on the issue.
> 
> Leaving this open if more bug reports flow in.

@qortex What is the command you use in the nx repo? IIRC, Nx's `@nrwl/node:node` executor has `watch` set as `true` by default, so you would be in a watch mode which could contribute to what you're seeing

**Comment by qortex** [comment]
> @qortex What is the command you use in the nx repo? IIRC, Nx's `@nrwl/node:node` executor has `watch` set as `true` by default, so you would be in a watch mode which could contribute to what you're seeing

Yes that is exactly the case. Thanks!
So it makes sense the bug shows up.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
