### ISSUE TITLE
CORS Enabling not working!

### ISSUE THREAD

**Issue by satinder1624** [nestjs/docs.nestjs.com#2471]
Hello,

I need help in enabling CORS policy. I am using NestJS React and GraphQL.

I tried this -> https://docs.nestjs.com/security/cors but it does not help for me. And, don't know what to do.

Thanks
![image](https://user-images.githubusercontent.com/73497748/192040317-cb3c3679-2b8e-4984-9478-a99d2a6cbf63.png)

**Comment by jmcdo29** [comment]
Please use our [Discord](https://discord.gg/nestjs) channel (Support). We are using GitHub to track Bug Reports, Feature Requests, and Regressions.
