### ISSUE TITLE
Documentation : prettier, eslint, vscode ?

### ISSUE THREAD

**Issue by cyrilchapon** [nestjs/docs.nestjs.com#2474]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Just coming to Nestjs, it came to my mind that Nest choices around code linting and formating are not clearly documented, and even not clearly stated.

Reading the codebase, 2 npm commands (`lint` / `format`), I can see some packages installed, some config files created, without any explaination. They don't seem to be called by any other command (unless `nest` cli call them magically... ?).

Searching "prettier" / "eslint" / "vscode" in the documentation search bar gives nothing. Searching through github issues leads to corners that don't actually help.

---------

Believe it or not, even after a decade coding in JS / TS, I personally never used prettier in my life (played with all possible eslint / standard and ts flavours though); and apparently Nest made such a choice, that IMHO should be at least stated. From an external point of view, Nest is just not really a framework in the sense of a "library", but rather also a CLI, a set of tools, and opinions. Linter and Formater are part of it.

### Describe the solution you'd like

The need is broad but can be simply expressed :
> As a developer, after installing nest and creating my first project — at least with default configuration, without touching anything else — I want to have a clear idea of the code formatting / styling choices, strategies and tooling involved.

Some examples of what I'd expect to read :

> Nest comes with eslint and prettier preinstalled and configured to work together. Configuration involves packages [eslint, prettier, this-eslint-plugin, etc.]

> Linting and formating can be run through command line, respectively `yarn format` / `yarn lint`

> Configuration is made through those 3 files [eslintrc, .prettierrc, etc.]

> In that default setup, the recommended VSCode extension to work with prettier is [that one].

----------

It could expand to eslint and prettier customization; but this is not my main point here. My main point is really around **default** config explaination.

### Teachability, documentation, adoption, migration strategy

The whole issue is a documentation request, see above.

### What is the motivation / use case for changing the behavior?

The issue is a documentation request, no "behavior change" involved.

**Comment by jmcdo29** [comment]
> The prettier + eslint part is apparently correctly addressed (properly configured to work together); but the implicit "documentation" issue (eg. making vscode working with it) is not.

Can you tell us how it doesn't work with VSCode as it is currently configured? I don't recall ever having an issue with VSC and linting a `nest new` project unless something upstream changed (like Typescript 4.8's AST that broke eslint for a little while)

**Comment by cyrilchapon** [comment]
@jmcdo29 as stated, nothing "doesn't work" here. It's a doc request.

I managed to put something working together with VScode without real effort actually. But I found nothing about afforementionned tooling on Nest doc

**Comment by jmcdo29** [comment]
> but the implicit "documentation" issue (eg. making vscode working with it) is not.

Sorry, this sounded a lot like we needed to document how to make it work with VSCode, hence my question. If it's just adding a mention of the tooling that should be pretty straightforward

**Comment by cyrilchapon** [comment]
As an expansion of my issue, here's is the page and paragraphs about testing : https://docs.nestjs.com/fundamentals/testing

I'd expect something similar for linting / formatting

**Comment by cyrilchapon** [comment]
I can try to PR this maybe. In my opinion a new page would be awesome. Right under "Testing" I guess

**Comment by jmcdo29** [comment]
I feel like a full page dedicated to the generated tooling might be a bit much. Though a section in the `Overview` page might do well, near the end saying "We generate configs for prettier and eslint. Here's what they do for your application" might be useful.

**Comment by cyrilchapon** [comment]
Alright. Doing

**Comment by Tony133** [comment]
We can follow this issue here https://github.com/nestjs/docs.nestjs.com/pull/2477 so we can close this issue, right?
