### ISSUE TITLE
Improve CQRS event handlers doc

### ISSUE THREAD

**Issue by CDelgrange** [nestjs/docs.nestjs.com#2476]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

The "problem" is already known, you can find details in [this issue](https://github.com/nestjs/cqrs/issues/409).

TLDR: When you start using CQRS events / event handlers, you get out of the traditional HTTP web context. There are multiple solutions to solve this behavior, but the point here, is that it's not documented anywhere and it can lead to unexpected crashes.

### Describe the solution you'd like

A simple **Hint** in the doc explaining that behavior and what to expect in order to react appropriately.

### Teachability, documentation, adoption, migration strategy

Here is what I would like to add to the doc:
![cqrs doc](https://user-images.githubusercontent.com/10831966/193198828-50fc284a-d9f8-46b4-a80b-2abb9cdeda29.png)

### What is the motivation / use case for changing the behavior?

It's not changing the behavior, it's just inform people for better communication and some time saved for everyone.

**Comment by CDelgrange** [comment]
@Tony133 No offense, but could you let met create that PR please ?
As you probably guessed thanks to the screenshot of the issue, I already made the changes. I don't know why - _probably because I'm not used to contribute to open source projects_ - but I thought that someone had to approve my new opened issue before pushing the code associated to it...
And because it's my first time to contribute to open source project I was "proud" to contribute following the whole process :sweat_smile:

**Comment by Tony133** [comment]
Hi @CDelgrange, no problem, as soon as you do the PR I close mine 👍

No, an issue does not have to be approved, to create a PR.

If you want future contributions to the NestJS repositories you directly open a PR with what you think needs to be changed, without creating an issue, then it will be evaluated and approved in code review.

Let's say it is a "faster" step.

**Comment by CDelgrange** [comment]
Thanks a lot @Tony133 👌 

Noted ! :)

**Comment by Tony133** [comment]
You're welcome, it's nothing. 😉👍

 I closed my PR

**Comment by Tony133** [comment]
This issue we can close since the merge has been done here: https://github.com/nestjs/docs.nestjs.com/pull/2486

**Comment by CDelgrange** [comment]
You're right 👍
