### ISSUE TITLE
Improving documentation readability (-useFactory +useValue).

### ISSUE THREAD

**Issue by Salloom99** [nestjs/docs.nestjs.com#2483]
## I'm submitting a suggestion for imporoving documentation.

- [ ] Regression
- [ ] Bug report
- [ ] Feature request
- [x] Documentation issue or request (new chapter/page)
- [ ] Support request

## Current behavior
In the "custom providers" page in "Non-service based providers" the example uses the "useFactory" method.

## Expected behavior
Isn't more convenient to use "useValue" instead.

## Minimal reproduction of the problem with instructions
Reading documentation.

## What is the motivation / use case for changing the behavior?
More understandable.

**Comment by kamilmysliwiec** [comment]
In this example, we rely on the `process.env.NODE_ENV` which might be populated lazily (hence, the use of `useFactory`).
