### ISSUE TITLE
DOCS: catProviders is not included in CatModule exports

### ISSUE THREAD

**Issue by Atsukoro1** [nestjs/docs.nestjs.com#2494]
## I'm submitting a issue to fix a minor mistake in nestjs documentation.

(Here)[https://docs.nestjs.com/recipes/mongodb#mongodb-mongoose] in the final CatsModule code, should be catProviders in exports.

- [ ] Regression
- [x] Bug report
- [ ] Feature request
- [x] Documentation issue or request (new chapter/page)
- [ ] Support request

## Current behavior
This is the error that it throws without including the catsProviders in CatModule exports

```text
Error: Nest can't resolve dependencies of the CatsService (?). Please make sure that the argument CAT_MODEL at index [0] is available in the AppModule context.

Potential solutions:
- If CAT_MODEL is a provider, is it part of the current AppModule?
- If CAT_MODEL is exported from a separate @Module, is that module imported within AppModule?
  @Module({
    imports: [ /* the Module containing CAT_MODEL */ ]
  })
```

## Expected behavior
Should work without errors and make it possible for us to use the cat schema in services.

## Minimal reproduction of the problem with instructions
```typescript
@Module({
  imports: [DatabaseModule],
  exports: [...catsProviders],
  controllers: [CatsController],
  providers: [
    CatsService,
    ...catsProviders,
  ],
})
export class CatsModule {}
```

## What is the motivation / use case for changing the behavior?
I was could not solve this problem or find some helpful information online, I want to help others so they will not make the same mistake in future.

## Environment

- Platform: Windows and Linux

**Comment by Tony133** [comment]
Hi @Atsukoro1, if it can help you, you can find a working example referring to the recipes for mongodb here: https://github.com/nestjs/nest/tree/master/sample/14-mongoose-base.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
