### ISSUE TITLE
[Documentation] Security /CSRF Protection Problem (Page refresh required)

### ISSUE THREAD

**Issue by MarazorQ** [nestjs/docs.nestjs.com#2527]
## [Documentation] Security /CSRF Protection Problem

- [ ] Bug report

## Current behavior

While working with security, I ran into a problem on this [page](https://docs.nestjs.com/security/csrf)

![Снимок экрана 2022-11-11 в 13 16 56](https://user-images.githubusercontent.com/60485417/201319438-1cdd9c8a-a710-409a-a1bc-0d539b81a617.png)

Unfortunately this [package](https://github.com/expressjs/csurf) has been deprecated

![Снимок экрана 2022-11-11 в 13 20 05](https://user-images.githubusercontent.com/60485417/201320408-738f435d-7697-4219-8dc2-ded4a7234c73.png)

## Expected behavior
You should update the documentation on this [page](https://docs.nestjs.com/security/csrf), and replace [csurf](https://github.com/expressjs/csurf#csurf) with something from [ this](https://www.npmjs.com/search?q=express%20csrf) for example

**Comment by kamilmysliwiec** [comment]
Docs updated ✅
