### ISSUE TITLE
Keyboard shortcut to focus search input

### ISSUE THREAD

**Issue by homostellaris** [nestjs/docs.nestjs.com#2625]
I'm referring to the docs a lot at the moment so it would be helpful if there was a keyboard shortcut like `/` or `command + k` to focus the search input.

Would you accept a PR for this?

**Comment by Tony133** [comment]
This problem can be closed, with the integration of the new version of Algolia v3, these keyboard shortcuts have been included. 🙌

<img width="1412" alt="new-search-bar" src="https://user-images.githubusercontent.com/11542387/227535614-ac138642-7cba-4b67-8410-7cae06b1a4d1.png">
