### ISSUE TITLE
csurf deprecated. Please suggest a new lib

### ISSUE THREAD

**Issue by kasir-barati** [nestjs/docs.nestjs.com#2665]
## I'm submitting a Documentation issue or request
As you may know [csurf](https://www.npmjs.com/package/csurf) is deprecated.

## Current behavior
In the [this doc page](https://8-0-0--docs-nestjs.netlify.app/security/csrf#use-with-express-default) which is related to csrf attack protection we still suggest to use csurf.

## Expected behavior
We can suggest something new like:
- [tiny-csrf](https://www.npmjs.com/package/tiny-csrf)
- [csrf](https://www.npmjs.com/package/csrf)
- [lusca](https://www.npmjs.com/package/lusca)

BTW I think tiny-csrf is a good alternative since it is easy to use and also it not a very complex with lots of security implementations that you may not use. And it also clarify it in its npm page that if you need very specific security requirements please use another lib and also refers to the [Cross-Site Request Forgery Prevention Cheat Sheet page](https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html)

## Minimal reproduction of the problem with instructions
Just do `npm i csurf` in your nestjs app

## What is the motivation / use case for changing the behavior?
Get rid of an annoying warning :joy: 

## Environment
Does not matter

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by kasir-barati** [comment]
Yes, I love it. So I'll create it.

**Comment by MinaFayez9** [comment]
I would also suggest [csrf-csrf](https://www.npmjs.com/package/csrf-csrf), and I would love to have an out of the box support for it

**Comment by kasir-barati** [comment]
@MinaFayez9 Would you please tell me what do you ment by "out of the box support for it"?

**Comment by MinaFayez9** [comment]
The library needs some configurations to work with NestJS, you can use it as a middleware or as a guard but in both ways you would need to do either a workaround in case of guard or hard code public endpoint(s) in case of middleware
So I would love to have some way from NestJS - if they see this library as worthy - to integrate with it more easily without workarounds

**Comment by kamilmysliwiec** [comment]
Since this one https://www.npmjs.com/package/csrf seems to be the most popular, let's use it for the docs

**Comment by micalevisk** [comment]
#2751
