### ISSUE TITLE
`bug` - incorrect behavior of the interface (when hovering over the search field, the interface begins to shake violently)

### ISSUE THREAD

**Issue by zharinov-nikita** [nestjs/docs.nestjs.com#2686]
![Видео без названия — сделано в Clipchamp](https://user-images.githubusercontent.com/101789452/228899476-6a41da9d-31cf-4d2c-9472-65818ae888dc.gif)

incorrect behavior of the interface (when hovering over the search field, the interface begins to shake violently)

The error occurs in:

1. `google chrome (without extensions)`
2. `windows 11`

I got the same problem in the `opera browser`

**Comment by kamilmysliwiec** [comment]
Fixed! Thanks for reporting
