### ISSUE TITLE
Cache documentation

### ISSUE THREAD

**Issue by MaksimKiselev** [nestjs/docs.nestjs.com#2689]
In [Caching](https://docs.nestjs.com/techniques/caching) section recommended to use `cache-manager-redis-store` but this **_unofficial store with totally incompatible implementation of CacheInterface_** https://github.com/dabroek/node-cache-manager-redis-store/issues/53#issuecomment-1325108666

I've done research and find correct solution - use official redis/ioredis cache stores.

See: https://github.com/dabroek/node-cache-manager-redis-store/issues/53#issuecomment-1473700342

## I'm submitting a...
- [+] Documentation issue or request (new chapter/page)

## Current behavior
https://github.com/dabroek/node-cache-manager-redis-store/issues/53#issuecomment-1325108666

## Expected behavior
https://github.com/dabroek/node-cache-manager-redis-store/issues/53#issuecomment-1473700342

## Minimal reproduction of the problem with instructions
-

## What is the motivation / use case for changing the behavior?
1) Off docs should be useful
2) Safe time for devs, because incorrectly implemented CacheInterface in `cache-manager-redis-store` package which also chages between versions it's evil and will broke app logic (dev - local cache store, prod - redis cache store === 💥 💔 ).

#### For Tooling issues:

- Node version: XX

- Platform:

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/docs.nestjs.com/pull/2703
