### ISSUE TITLE
Burger menu scroll not working on Mozilla Firefox

### ISSUE THREAD

**Issue by ArielCorte** [nestjs/docs.nestjs.com#2811]
## I'm submitting a...
- [x] Bug report

## Current behavior
I can open the left burger menu and spread the sections, but I can't scroll the menu. Rolling the mouse wheel only scrolls the main page, even if the cursor is hovering the menu. Even inspecting the page and putting it in mobile display the scroll doesn't work. It works in Chrome though, both linux and android.

## Expected behavior
The desired behavior should be to scroll when hovering over the menu and rolling the mouse wheel, like it does in Chrome.

## Minimal reproduction of the problem with instructions
Open Mozilla Firefox
Go to docs
Open burger menu
Can't scroll it :(

## What is the motivation / use case for changing the behavior?
To see all sections

#### For Tooling issues:

- Node version: XX

- Platform: Linux

**Comment by jmcdo29** [comment]
I'm not having this issue, and Firefox is my daily browser. 

<details>

<summary>Firefox Details and Version</summary>

Mozilla Firefox 115.0.3 20230727224807 20230727224807 
Mozilla Firefox for Arch Linux
archlinux - 1.0

</details>

**Comment by Tony133** [comment]
Using the macOS version of Firefox works perfectly (see clip).

https://github.com/nestjs/docs.nestjs.com/assets/11542387/3d81c2f8-5644-467d-8f2f-254b17a84f84

**Comment by kamilmysliwiec** [comment]
I can't reproduce this issue either
