### ISSUE TITLE
Is the Mongo technique guide correct about MongooseModule.forFeature name Cat.name?

### ISSUE THREAD

**Issue by antoniormrzz** [nestjs/docs.nestjs.com#2815]
## I'm submitting a...

- [ ] Regression 
- [ ] Bug report
- [ ] Feature request
- [x] Documentation issue or request (new chapter/page)

## Current behavior
[MongoDB Technique](https://docs.nestjs.com/techniques/mongodb)
In all instances of forFeature and forFeatureAsync, Cat.name is used as name. Cat is the class defined with `@Schema` decorator. I looked at the code for Schema decorator but didn't see anything there that was related either.  
```
import { Cat, CatSchema } from './schemas/cat.schema';

@Module({
  imports: [MongooseModule.forFeature([{ name: Cat.name, schema: CatSchema }])],
  controllers: [CatsController],
  providers: [CatsService],
})
```

## Expected behavior
Shouldn't it just be `"Cat"`?
`name: "Cat"`
#### Others:
If yes, I'd like to be the one doing that PR 😄

**Comment by jmcdo29** [comment]
It can be `"Cat"` or `Cat.name`. The `.name` is something that exists on all Functions in JavaScript, so we make use of that often times for easy class based injection tokens.

**Comment by antoniormrzz** [comment]
@jmcdo29 Thank you so much! I learned something new today. I don't do much class based JS lately, and I had never came across this. I guess a little more confusing is the fact that name exists for Cat. I was like, name isn't static or anything. Closing 👍
