### ISSUE TITLE
Add mention about testing module limitation on usage of `HttpAdapterHost.httpAdapter`

### ISSUE THREAD

**Issue by micalevisk** [nestjs/docs.nestjs.com#2823]
I believe we should mention about this: https://github.com/nestjs/nest/issues/8076#issuecomment-926542597 limitation of `Test.createTestingModule` somewhere in the docs (peharps as a sub-section of https://docs.nestjs.com/fundamentals/testing#end-to-end-testing or at https://docs.nestjs.com/faq/http-adapter page) because the project generated by Nest CLI is using it for E2E and users may face errors like this one: https://github.com/notiz-dev/nestjs-prisma/issues/74 when some 3rd-party nestjs lib uses `HttpAdapter` under the hood

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/docs.nestjs.com/commit/eb78ef94a4bc9ca2aab05ee25038a3cb143de638
