### ISSUE TITLE
Add mention for `forceCloseConnections` feature of `NestFactory.create`

### ISSUE THREAD

**Issue by micalevisk** [nestjs/docs.nestjs.com#2840]
That feature introduced in Nestjs v9.2.0 by this PR: https://github.com/nestjs/nest/pull/10345 isn't mentioned anywhere in the docs site. 

Not sure where we can mention about that tho

**Comment by kamilmysliwiec** [comment]
Perhaps we should add a new chapter under FAQ category?

**Comment by micalevisk** [comment]
@tolgap do you have any other suggestion?

**Comment by tolgap** [comment]
> @tolgap do you have any other suggestion?

I think FAQ would be the right directory. Devs will most likely run into the "hanging of the application" when they use `.enableShutdownHooks()` in their app. So we could add a chapter about why the app might not restart correctly in watch mode and `.enableShutdownHooks()`. 👍
