### ISSUE TITLE
GqlAuthGuard - how to provide request

### ISSUE THREAD

**Issue by myeveryheart** [nestjs/docs.nestjs.com#286]
[ ] Bug report

I see the doc:
In order to use AuthGuard together with GraphQL, you have to extend the built-in AuthGuard class and override getRequest() method.

```
@Injectable()
export class GqlAuthGuard extends AuthGuard('jwt') {
  getRequest(context: ExecutionContext) {
    const ctx = GqlExecutionContext.create(context);
    return ctx.getContext().req;
  }
}
```

Ok, there is no getRequest for override.
And where should I use the GqlAuthGuard.
Maybe the doc can be more specific.
:D

**Comment by yostools** [comment]
Is there any new information? I'm hanging in the same place right now.

**Comment by cesar3030** [comment]
You should use it instead of `AuthGuard`
Example:
```ts
  @Query(returns => Dog)
  @UseGuards(GqlAuthGuard)
  dog(@Args('id') id: string,): Promise<Dog> {
    return this.dogsService.findById(id)
  }
```

**Comment by krishanik** [comment]
authentication part of the docs is still a mess

**Comment by kamilmysliwiec** [comment]
https://docs.nestjs.com/techniques/authentication#graphql
