### ISSUE TITLE
Suggestion for Document Function Display

### ISSUE THREAD

**Issue by Snowkei** [nestjs/docs.nestjs.com#2915]
Can we add a global search feature to the document to make it easier to find

**Comment by jmcdo29** [comment]
Like the one that exists? 
![image](https://github.com/nestjs/docs.nestjs.com/assets/28268680/48dd8761-84f1-4edc-99ed-bdca3b9e36a3)

**Comment by Snowkei** [comment]
Perhaps due to internal network issues, my page was not fully displayed and is now functioning normally. Thank you
