### ISSUE TITLE
Add docs on typescript-only features of `nest generate` commmand

### ISSUE THREAD

**Issue by micalevisk** [nestjs/docs.nestjs.com#2930]
Looks like there's no mention about using `nest generate resource` in a JS project

![image](https://github.com/nestjs/docs.nestjs.com/assets/13461315/b14bf193-cb61-474a-8b93-69a7c5f985a3)

Ideally, we should mention it at https://docs.nestjs.com/cli/usages#nest-generate

https://github.com/nestjs/nest/issues/12978 please @AlvesJorge feel free to address this issue.

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/docs.nestjs.com/pull/2931
