### ISSUE TITLE
How can I send header with kafka clientKafka=>send

### ISSUE THREAD

**Issue by nipu-softic** [nestjs/docs.nestjs.com#2950]
```  send(message: string, data: any, headers?: Record<string, string>) {
    return new Promise((resolve, reject) => {
      this.authClient.send(message, JSON.stringify(data)).subscribe({
        next: (response) => {
          resolve(response);
        },
        error: (error) => {
          reject(error);
        },
      });
    });
  }
```

controller function

 ```
async getAllUser(filter: FindAllDto) {
    return await this.send(GET_USERS, filter);
  }
```

I want to received header in auth-service in kafka contex

```
  @Get()
  @MessagePattern(GET_ROLES)
  async findAll(
    @Payload(new ZodPipe(findAllSchema)) payload: FindAllDto,
    @Ctx() context: KafkaContext,
  ) {
    const response = await this.rolesService.findAll(payload);
    return this.res.successResponse({
      data: response,
      status: 200,
      message: 'Role list found successfully',
      request: {
        topics: context.getTopic(),
      },
    });
  }
```

**Comment by Tony133** [comment]
Hi @nipu-softicfor, for this type of question try to use the support [discord](https://discord.com/invite/G7Qnnhy) channel

**Comment by kamilmysliwiec** [comment]
Thank you for taking the time to submit your report! From the looks of it, this could be better discussed on our Discord. If you haven't already, please join [here](https://discord.gg/nestjs) and send a new post in the #⁠ 🐈 nestjs-help forum. Make sure to include a link to this issue, so you don't need to write it all again. We have a large community of helpful members, who will assist you in getting this to work.
