### ISSUE TITLE
What approach should I follow to translate the doc?

### ISSUE THREAD

**Issue by cserron** [nestjs/docs.nestjs.com#3]
Hi Kamil, 
I was wondering what's the approach you'd like people to follow when translating the doc into different languages.
So far I've seen the content is part of the html part of the component.
Should we create the translated version of the doc as an independent ng project in a different branch and then send a PR?

Let me know what is the approach you'll like people to follow when delivering the translated versions of the site. 

Best,
Chris.

**Comment by kamilmysliwiec** [comment]
Hi @cserron,
In the best case, we should try to use https://angular.io/guide/i18n, but it needs some additional effort. I can take care about it, but in the meantime maybe let's just keep translating docs in the independent project :)

**Comment by quen2404** [comment]
Hi @kamilmysliwiec, is there any news about this ? I want to translate the documentation in my native language (french).

**Comment by linsolas** [comment]
Hello,

I would be happy to participate to the translation too (in french also, @quen2404).
Any news regarding a support of i18n / move to markdown?

**Comment by mazyvan** [comment]
I can help with Spanish 👍

**Comment by ShGKme** [comment]
As most of content is in markdown, i18n seems to be not the best solution. What about just splitting markdown doc files into language subdirectories like `content/en/cli`, `content/sp/cli`, `content/ru/cli` and then choose content according to subdomain | path?

**Comment by ShGKme** [comment]
If we create a translation, could we build translated docs.nestjs.com website and host it anywhere? Would it be legal?

**Comment by rlaace423** [comment]
@ShGKme @Hwan-seok  I think current master branch doesn't use `content/` at all. Seems that It just renders html files inside each components.

So, it seems taht more discussion required.
If direction is set, I'll start translation Korean. #890

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/docs.nestjs.com/issues/3
