### ISSUE TITLE
Issues and PR Summary

### ISSUE THREAD

**Issue by Tony133** [nestjs/docs.nestjs.com#3003]
Hi 👋🏻, 

I open this issue to summarize some issues that can be closed and PR that can be merged, I put the list below:
 
#### Issues that can be closed

- https://github.com/nestjs/docs.nestjs.com/issues/2474 PR done here: https://github.com/nestjs/docs.nestjs.com/pull/2477

- https://github.com/nestjs/docs.nestjs.com/issues/2431 PR done here: https://github.com/nestjs/docs.nestjs.com/pull/2461

- https://github.com/nestjs/docs.nestjs.com/issues/2127 PR done here but closed https://github.com/nestjs/docs.nestjs.com/pull/2129 , so I would say you can close this issue

#### PR with revisions:

  - https://github.com/nestjs/docs.nestjs.com/pull/2704

  - https://github.com/nestjs/docs.nestjs.com/pull/2630
  
  - https://github.com/nestjs/docs.nestjs.com/pull/2703
  
  - https://github.com/nestjs/docs.nestjs.com/pull/2766
  
  - https://github.com/nestjs/docs.nestjs.com/pull/2773
  
  - https://github.com/nestjs/docs.nestjs.com/pull/2810
    
  - https://github.com/nestjs/docs.nestjs.com/pull/2466
  

#### PR Duplicate:  

- https://github.com/nestjs/docs.nestjs.com/pull/2778

@kamilmysliwiec  @jmcdo29  @micalevisk this is a short summary to update the documentation a little bit, I realize that every day you get a lot of notifications, so I thought I would make a list, I have been wanting to do this for a while but haven't had much time these months due to work commitments.  

As soon as you find some time take a look at it. 🙂

I hope I have been helpful to you

Have a good week  🙂

**Comment by micalevisk** [comment]
thank you for this

I don't have permissions to close issues here tho

**Comment by kamilmysliwiec** [comment]
Thanks @Tony133!
