### ISSUE TITLE
Request to add version selection function

### ISSUE THREAD

**Issue by develjsw** [nestjs/docs.nestjs.com#3044]
## I'm submitting a...

- [x] Feature request

## Current behavior

<img width="1197" alt="image" src="https://github.com/nestjs/docs.nestjs.com/assets/87625837/49c36b00-175d-4e95-9b9d-daf9dc8f3cbd">

## Expected behavior

You cannot select the version.

## What is the motivation / use case for changing the behavior?

You can move by entering the version in the url but this provides a bad experience for the user.
Therefore, it would be good if you provide a URL selection function.

#### For Tooling issues:

- Node version: 18.19.0

- Platform: Windows

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/docs.nestjs.com/pull/1638
