### ISSUE TITLE
service worker keeps stale website in cookie and doesn't update

### ISSUE THREAD

**Issue by basudebpal** [nestjs/docs.nestjs.com#31]
Can't reproduce the issue anymore.
Yesterday i started to work on graphql integration of nestjs. On a different laptop today i opened the docs page on chrome to find that no docs for graphql. Opened the website on firefox on same laptop and saw the new docs website. so, I check the cookies and find that it's keeping the page in a folder named "**service worker**" and keeps serving that. I am not well versed in service workers and offline caching, but, stale docs page (about 1 month old) is not good. Didn't capture any screenshots before i cleared the cookies. Please ignore if already taken action. 
P.S. - Awesome project :) keep up the good work :)

**Comment by kamilmysliwiec** [comment]
Hi @basudebpal,
Yeah, that's true. There're some issues with the docs caused by the service worker which is removed already (for now). Ppl need to remove SW manually for now.
And thanks 🙂
