### ISSUE TITLE
OpenAPI CLI Plugin Integration with jest@^29

### ISSUE THREAD

**Issue by JenniferStamm** [nestjs/docs.nestjs.com#3160]
https://github.com/nestjs/docs.nestjs.com/blob/3c9497898cb1f9c3013911672bbb3f5ea82d6203/content/openapi/cli-plugin.md?plain=1#L246

I'd appreciate if the docs would give a heads-up that the first described approach is deprecated. Readers receive the info only a couple lines below that there is a newer approach:
https://github.com/nestjs/docs.nestjs.com/blob/3c9497898cb1f9c3013911672bbb3f5ea82d6203/content/openapi/cli-plugin.md?plain=1#L280

One could simply extend the sentence to mention the version:
```
To enable the plugin when using jest@<29, [...]
```

On my screen size, the second approach wasn't visible without scrolling, so I lucky to notice it before trying out the first approach.

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by JenniferStamm** [comment]
@kamilmysliwiec I opened a PR. I couldn't figure out how to put line breaks in the commit message when editing on the Github website. I hope it still fits the contribution guidelines when the extra information is in the commit description.

**Comment by kamilmysliwiec** [comment]
Thank you @JenniferStamm. Let's track this here https://github.com/nestjs/docs.nestjs.com/pull/3162
