### ISSUE TITLE
Incorrect documentation for GraphQL code first approach?

### ISSUE THREAD

**Issue by LandazuriPaul** [nestjs/docs.nestjs.com#339]
## I'm submitting a...

<pre><code>
[x] Documentation issue
</code></pre>

## Current behavior

The configuration example for the code first approach (https://docs.nestjs.com/graphql/quick-start#code-first) uses both `typePaths` and `autoSchemaFile` properties. Is it intended? I would have thought that the second one (related to the code first approach) makes the first one silent. Am I wrong?
 
## Expected behavior

If there is any reason for this specific configuration, a quick hint could enlighten many people, as this other issue nestjs/graphql/issues/195 points out the same incoherence. Otherwise, I guess the example should be fixed.

Have a nice day!

**Comment by kamilmysliwiec** [comment]
Thanks for reporting! Just fixed that :)
