### ISSUE TITLE
🔍 Improving search on docs with Algolia's DocSearch

### ISSUE THREAD

**Issue by Shipow** [nestjs/docs.nestjs.com#428]
Hello Nestjs team,<br><br>I've noticed that your documentation could take advantage of our <a href='https://community.algolia.com/docsearch/'>DocSearch</a> initiative.<br><br>So, we went on <b>trying to improve the search and came up with this demo:</b><br>💖<a href='https://docsearch-nestjs.netlify.com/'>Try out the search here</a> 💖 (we've added docsearch.js to a mirror of the documentation).<br><br>Algolia's DocSearch is crawling the website every 24h, extracting content from every page. Then this content is made searchable by Algolia's API and exposed to the user with a searchbox and its custom dropdown.<br><br>You might have already used DocSearch on some popular docs like <a href='https://getbootstrap.com/docs/4.1/getting-started/introduction/'>Bootstrap</a>, <a href='https://vuejs.org/v2/guide/'>Vue</a>, <a href='https://api.jquery.com/'>jQuery</a>, <a href='https://reactjs.org/docs/getting-started.html'>React</a>, <a href='https://jestjs.io/docs/en/api'>Jest</a>, <a href='https://docs.gitlab.com/'>Gitlab</a>, <a href='https://docs.brew.sh/'>Brew</a>, <a href='https://devcenter.heroku.com/'>Heroku</a>, <a href='https://support.invisionapp.com/'>Invision</a>, <a href='https://stripe.com/docs'>Stripe</a>, <a href='https://www.algolia.com/doc/'>Algolia</a>, ...<br>So far, we are maintaining our crawler for 1500+ docs.<br><br><img src='https://res.cloudinary.com/hilnmyskv/image/upload/v1558102381/docsearch-dropdown.png' alt='docsearch autocomplete preview'><br><br><ul><li><a href='https://community.algolia.com/docsearch/'>DocSearch</a> is fast, it handles typos and highlighting.</li><li>Search results jump directly to the matching part of the page.</li><li>Whenever your markup changes you can <a href='https://github.com/algolia/docsearch-configs/blob/master/configs/nestjs.json'>customize the configuration</a> on DocSearch repository.</li><li>You'll also have access to a dashboard of the most queried terms, as well as those that yields no results. We found it to be a very good way of knowing how to improve our documentation.</li><li>DocSearch is and will remain <b>FREE</b> (provided by <a href='https://www.algolia.com/'>Algolia</a>).</li></ul><br><b>Are you interested? 👍 👎</b><br><br><br>Ping @shipow or @s-pace<br>

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this? :)

**Comment by s-pace** [comment]
Sure, do we need to PR https://github.com/nestjs/docs.nestjs.com? @kamilmysliwiec 🙏

**Comment by kamilmysliwiec** [comment]
Yes, exactly :)

**Comment by s-pace** [comment]
I have tried to insert the snippet but the `<script/>` tags are executed before the page is rendered. We can't select the input since it is not created yet. Do you have any clue ?

**Comment by kamilmysliwiec** [comment]
Perhaps you can dynamically add script tag inside the Angular component lifecycle hook (after view is initialized `ngAfterViewInit`)

**Comment by s-pace** [comment]
👋 @kamilmysliwiec 

I have updated my fork with the great help of @tkrugg. The search works. This branch still needs a better integration within the header but I wanted to have your feedback first. 

What is the best position for the search bar? Having the search bar within the menu `.menu-wrapper` limit the search to the desktop version.

Any help/contribution is welcome.

**Comment by kamilmysliwiec** [comment]
Can you create a PR to this repo? That should generate the website preview

**Comment by s-pace** [comment]
Sure WIP: #659

**Comment by johnbiundo** [comment]
@s-pace Looks fantastic!  Can't wait to deploy!

**Comment by s-pace** [comment]
Great news @johnbiundo Happy to help!

**Comment by kamilmysliwiec** [comment]
Search has been added!

**Comment by kamilmysliwiec** [comment]
Hey @Shipow! Not sure if you're still working at Algolia - but it seems that our application got blocked. I sent a support request but no response so far

**Comment by s-pace** [comment]
👋  all,
Just chiming in to also tag @shortcuts who always does magic on these topics

**Comment by shortcuts** [comment]
thanks for the ping @s-pace <3

@kamilmysliwiec let me know how I can help, you can reach out [via twitter](https://twitter.com/sh0rtcts) if it's easier!

**Comment by shortcuts** [comment]
ok took a look at https://docs.nestjs.com/ and it seems you are still using the [old application](https://docsearch.algolia.com/docs/migrating-from-legacy), TLDR here's the new credentials to use: 
- appID: SDCBYAN96J
- apiKey: 6d1869890dab96592b191e63a8deb5b5
- indexName: nestjs

**Comment by kamilmysliwiec** [comment]
Thank you @shortcuts & @s-pace! Any chance you can grant me access to the search stats for the new app too? mail@kamilmysliwiec.com (I can't see it in the dashboard now)

**Comment by shortcuts** [comment]
> Any chance you can grant me access to the search stats for the new app too?

Sure, sending you the invita in DMs
