### ISSUE TITLE
Module improvements/questions

### ISSUE THREAD

**Issue by guidsdo** [nestjs/docs.nestjs.com#435]
## I'm submitting a...
<pre><code>[ ] Regression
[ ] Bug report
[ ] Feature request
[x] Documentation issue or request (new chapter/page)
</code></pre>

## Current behavior
Currently the `module` explanation page confuses me a bit. I wanted to create a PR with some improvements, but I don't know all the rules. Here are some quotes + questions:

### **`imports` explanation** (Line 22)
Original: `the list of imported modules that export the providers which are required in this module`
Improvement: `external modules of which their exported providers can be used in this module`
Question: Can providers also be added to this set?

### **`exports` explanation** (Line 26)
Original: `the subset of providers that are provided by this module and should be available in other modules which import this module`
Improvement: `providers which will be available for other modules that import/depend on this module`
Question: I saw in the `Module re-exporting` part, that modules can also be exported. This should be added in this explanation if that's correct.

## General missing information
* What happens if you receive a module from multiple sources? Is that allowed? Will your app crash? 
* How do controllers work if you have multiple modules? How does the framework choose which one to use if multiple have the same path?
* A picture with a dependency graph of modules, services and controllers. This can be simple of course.

**Comment by kamilmysliwiec** [comment]
Hey @guidsdo,
Thanks for your feedback. If you are interested, PRs are welcome (every page is written in the markdown format, hence, it should be fairly easy to contribute)
