### ISSUE TITLE
Angular Guide/Documentation

### ISSUE THREAD

**Issue by tayambamwanza** [nestjs/docs.nestjs.com#480]
I recently discovered Nestjs and it looks really awesome, I learnt about it through the talks at ng-conf and ngVikings. 

One of the things that really drew me is the fact that as an Angular developer I can transfer a lot of my experience and get started quicker.

What prompted me to make this issue is that in the **ngVikings 2019** conf you mentioned we need to just import **AngularModule**, and I wasn't sure where that was from, _so I checked the docs and didn't find anything_ :(

![Screenshot from 2019-06-14 20-16-02](https://user-images.githubusercontent.com/11971384/59529437-5799e500-8ee1-11e9-868b-2b0acaf20fb3.png)

The problem is that there's virtually no Angular Guides or documentation on the site. 

**I understand that Nestjs is platform agnostic**, but when **one of the biggest selling points is that Angular developers will find it familiar** I think that some **official documentation would go a long way to driving adoption from the angular community.**

**This is an awesome project and I would really love to see it grow**. So I just want it to be easier for Angular devs who find the syntax easier to grasp to **have more information for set up**.

**Comment by johnbiundo** [comment]
@tayambamwanza I think this is a good idea.  I'd like to put together a recipe page for people starting out with Nest for an Angular project. I have a few ideas, but do you have any particular questions/comments that should be addressed?

**Comment by tayambamwanza** [comment]
@johnbiundo That's fantastic news, well it's been a while since I asked this questions so the ideas aren't fresh in my mind, I'll come back to this once I'm ready.

I figured out a workflow after trying a bajillion (hyperbole) things, it's simple once you get the hang of it.

- Install angular cli,
- install nest cli

`ng new my-project` (test if app is working by running ng serve)
`ng add @angular/pwa` (nestjs universal has this as a dependency)
`ng add @nestjs/ng-universal` (nestjs config is in "server" folder)

Tada you have an Angular universal app

Test that it's working by building the project `npm run build:ssr`

Wait for the build to finish, then run `npm run serve:ssr`

Go to _localhost:4000_ and you should see the app running

Check SEO compatibility using lighthouse audit

- Docs for deployment would be nice
- Keep in mind not all UI libraries support SSR, check support beforehand (NG-Bootstrap has good support)

I think it's crucial to walkthrough config first, **without any** additional components, controllers, services being generated, just make sure config works, then start adding "custom" code. This way problems can be identified with the config easier.

It's such a good system when it works, I was so intimidated by server side rendering until I got this to work, there's potential for a lot of angular devs to adopt nest just for this feature alone.

**Comment by johnbiundo** [comment]
@tayambamwanza Wow, impressive recipe, thanks for sharing!  As you mentioned, if more comes back to you on this topic, please share here and we'll eventually get some of this into the docs.  Thanks again!
