### ISSUE TITLE
Documentation: Swagger: Working with enums

### ISSUE THREAD

**Issue by allanlykkechristensen** [nestjs/docs.nestjs.com#507]
In your online documentation about Swagger and Working with enums you write:

> To be able for SwaggerModule to identify an Enum, we have to manually set the enum property on @ApiModelProperty with an array of values.

However, couldn't this be done using `Object.keys(NameOfEnum)` instead of providing the values manually. Providing the values manually increases maintenance. E.g.

With this enum

```
export enum UserRole {
  Admin = 'Admin',
  Moderator = 'Moderator',
  User = 'User',
}
```

Instead of 

```
@ApiModelProperty({ enum: ['Admin', 'Moderator', 'User']})
role: UserRole;
```

You could do:
```
@ApiModelProperty({ enum: Object.keys(UserRole) })
role: UserRole;
```

**Comment by engmsaleh** [comment]
Hi @allanlykkechristensen When I do as you suggested I get both values and keys as options for the enum on the Swagger doc, for example I have this enum 
```
export enum ServiceTypeEnum {
  All = 0,
  BillPay,
  TopUp,
  Remittance,
  WageCredit,
  Promo,
  ReferralAmount,
}
```
```  @ApiModelProperty({
    enum: Object.keys(ServiceTypeEnum),
  })
  service_type: ServiceTypeEnum;```

I got the following on Swagger doc
<img width="983" alt="Screen Shot 2019-08-18 at 7 09 46 AM" src="https://user-images.githubusercontent.com/462150/63220409-36769e80-c187-11e9-931c-e35dc3017c58.png">

**Comment by lazarljubenovic** [comment]
It's not that trivial to get all enumeration values. There are some tricks to it for certain special cases (eg. numerical enumeration without skipping numbers), but in general it cannot even always be done (eg. with `const enum`). I tried battling this in a few separate occasions, and in the end figured that it's the best to just list all the enum values in an array and remember to maintain it. _Maybe_ build a linter rule if you have THAT many enums?

More info here:

- https://github.com/Microsoft/TypeScript/issues/17198
- https://stackoverflow.com/questions/44230998/how-to-get-a-random-enum-in-typescript

**Comment by kamilmysliwiec** [comment]
Using the approach already described in the docs is a recommended one. Otherwise, you can face side-effects as described above.
