### ISSUE TITLE
Clarify docs for Inheritance with Exception Filters

### ISSUE THREAD

**Issue by raffomania** [nestjs/docs.nestjs.com#531]
## Is your feature request related to a problem? Please describe.
The [docs for exception filters](https://docs.nestjs.com/exception-filters) provide contradicting information. First, they say:
> Filters that extend base classes have to be instantiated by the framework itself (don't manually create instances using the new operator). 

then, a few sentences later:
> You can use a global filter that extends the base filter by injecting the HttpServer reference.
```
 app.useGlobalFilters(new AllExceptionsFilter(httpAdapter));
```

## Describe the solution you'd like
Remove either the warning or update the code example on how to use children of `BaseExceptionFilter` without instantiating them manually.

**Comment by johnbiundo** [comment]
@kamilmysliwiec I can edit this.  Would it be accurate to say "Method-scoped and Controller-scoped filters that extend the `BaseExceptionFilter` should not be instantiated with `new`. Instead, let the framework instantiate them automatically."

And then down lower: "Global filters **can** extend the base filter and need to inject an `HttpServer` reference, as shown below.  In this case, you **must** instantiate the custom filter yourself."

**Comment by kamilmysliwiec** [comment]
> In this case, you must instantiate the custom filter yourself

You can also use `APP_FILTER` to mount it globally (so it's not a requirement) cc @johnbiundo
