### ISSUE TITLE
Please add section to be able to comment or ask question in documentation pages

### ISSUE THREAD

**Issue by RezaRahmati** [nestjs/docs.nestjs.com#537]
## Is your feature request related to a problem? Please describe.

As a user of nestjs I would like to be able to ask question or give feedback about documentations in the page I view the content.

## Describe the solution you'd like

Microsoft recently added this feature, see this [example](https://docs.microsoft.com/en-us/azure/container-instances/container-instances-volume-azure-files) , scroll to bottom of page, then in the bottom of page if you click on "Send feed back about this page", then you can give your feedback and an item will be created on their github page and it's very cool.  

## What is the motivation / use case for changing the behavior?

I read the Logging section of nestjs document, and find out there is nothing about how to use it, after googling find out the others also having same issue with that page, so why not to give feedback or even participate in completing the documentation, and better to be able to track them via github issues

**Comment by kamilmysliwiec** [comment]
Wouldn't it be easier to just add a link to the github repo below every chapter? I don't think that we should really build a new feature in the docs when we can just direct people to github issues.

**Comment by johnbiundo** [comment]
@BrunnerLivio Would it be possible to have a dynamic link inserted in the footer that would appear on each doc page and have a link to the corresponding repo markdown page?  I.e., it would automatically know the file name so we wouldn't have to maintain it/would automatically be added if we add new pages?

**Comment by BrunnerLivio** [comment]
@johnbiundo Yup definitely possible. I can have a look :)

**Comment by RezaRahmati** [comment]
> Wouldn't it be easier to just add a link to the github repo below every chapter? I don't think that we should really build a new feature in the docs when we can just direct people to github issues.

Yes, this is possible, but it matters of being user friendly to readers, sometimes different people have same question, so when I browse questions related to the same page I might find my answer as well. Also if you take a look at the link I provides from Microsoft site, you will see how easy is to add a comment (or ask a question) with out even knowing that it will go to github.

**Comment by kamilmysliwiec** [comment]
People would start asking technical questions right in the docs - like, how can I create module X? This is something that already happens very frequently on the github, and we should try to avoid adding another place that would lead to such things.

**Comment by johnbiundo** [comment]
Github link is now added.  Thanks for pointing us in this direction @RezaRahmati !

I'm going to close this one now.

**Comment by RezaRahmati** [comment]
@johnbiundo thanks, may I ask what is the change (in the UI) and how to use it?

**Comment by johnbiundo** [comment]
@RezaRahmati 

Click as shown below (upper right corner of each page) and it will take you to a Github page for the doc where you can edit/submit PRs.

![image](https://user-images.githubusercontent.com/6937031/61896540-0ad70000-aeca-11e9-8027-82f2b9dadd93.png)
