### ISSUE TITLE
Navigation menu not scrollable on iOS 11.3

### ISSUE THREAD

**Issue by BorntraegerMarc** [nestjs/docs.nestjs.com#58]
See attached screen recording. I think it only happiness on iOS
![becc5196-9de4-4603-bb2e-394f91baf199](https://user-images.githubusercontent.com/7549295/38190934-d1c3a200-3666-11e8-85c3-e9b71c8c74be.gif)

**Comment by kamilmysliwiec** [comment]
Thanks for reporting (+video). It is fixed in new docs https://docs.nestjs.com/v5/

**Comment by BorntraegerMarc** [comment]
Thanks @kamilmysliwiec But now the burger menu is always closed on desktop, after choosing an item -> it should always stay open on Desktop browsers in my opinion :)

Using google chrome 65 on Windows

**Comment by kamilmysliwiec** [comment]
Fail, my bad. Pushing fix now 😅 thanks @BorntraegerMarc
