### ISSUE TITLE
Add passport-headerapi example

### ISSUE THREAD

**Issue by vdusauto** [nestjs/docs.nestjs.com#648]
I have been trying to implement passport-headerapi under nestjs, with lo luck so far.
How is the authenticate function called ?

Would it be possible to have an example in the documentation?

Thanks in advance !

**Comment by kamilmysliwiec** [comment]
Unfortunately, we can't cover every existing passport strategy in the docs. 
You can try using our [Discord](https://discord.gg/G7Qnnhy) channel for support.
