### ISSUE TITLE
Documentation error in dynamic modules

### ISSUE THREAD

**Issue by yohancourbe** [nestjs/docs.nestjs.com#672]
The final code example for dynamic modules in https://docs.nestjs.com/fundamentals/dynamic-modules contains an error: exported service `ConfigService` is not provided.

```
import { DynamicModule, Module } from '@nestjs/common';

import { ConfigService } from './config.service';

@Module({})
export class ConfigModule {
  static register(options): DynamicModule {
    return {
      module: ConfigModule,
      providers: [
        {
          provide: 'CONFIG_OPTIONS',
          useValue: options,
        },
      ],
      exports: [ConfigService],
    };
  }
}
```

Working example provided has `ConfigService` exported: https://github.com/nestjs/nest/blob/master/sample/25-dynamic-modules/src/config/config.module.ts#L16

**Comment by kamilmysliwiec** [comment]
cc @johnbiundo

**Comment by johnbiundo** [comment]
@yohancourbe Thank you.  PR #678 in process to fix this.
