### ISSUE TITLE
Weird design for old v4.0 docs

### ISSUE THREAD

**Issue by BorntraegerMarc** [nestjs/docs.nestjs.com#77]
See Screenshot: On mac Chrome:
![screen shot 2018-05-13 at 17 28 42](https://user-images.githubusercontent.com/7549295/39968811-42179ed0-56d3-11e8-95da-76a6f67d3963.png)

**Comment by BorntraegerMarc** [comment]
And on mobile safari the page is not even loaded :/ ios v11.3
![85f91a67-a36c-405e-bdda-8c4904be365d](https://user-images.githubusercontent.com/7549295/39968835-94d7256e-56d3-11e8-8a09-f3b2bce27afe.png)

**Comment by jienco** [comment]
The page https://docs.nestjs.com/v4/ does not load for me in Chrome for Mac, with the following JS error in the console:

```
Uncaught SyntaxError: Unexpected token <
```

**Comment by BorntraegerMarc** [comment]
I believe I also tested it in incognito mode when I opened this bug.

Btw: the docs seem to have quite some issues with caching. Should we adapt the caching strategy? Not sure where the code for the caching is
