### ISSUE TITLE
How are the flow charts created?

### ISSUE THREAD

**Issue by idev247** [nestjs/docs.nestjs.com#8]
For example, these charts:

https://github.com/nestjs/docs.nestjs.com/raw/develop/src/assets/Guards_1.png
https://github.com/nestjs/docs.nestjs.com/tree/develop/src/assets

**Comment by kamilmysliwiec** [comment]
Hi @idev247,
Yeaaah, I know they're not perfect. I have put them to make an understanding process just **a little bit** easier. There's no fixed convention between them.

**Comment by idev247** [comment]
I like them. I was just wondering if there was an app that created them with that style.

**Comment by kamilmysliwiec** [comment]
Nope, my friend made them for me :)
