### ISSUE TITLE
Docs: api differences with type-graphql

### ISSUE THREAD

**Issue by stewartrule** [nestjs/docs.nestjs.com#812]
## I'm submitting a...

<pre><code>
[x] Documentation issue or request
</code></pre>

## Current behavior

Following the graphql [code first](https://docs.nestjs.com/graphql/quick-start#code-first) approach it seems there are some differences with using subscriptions and resolvers in `type-graphql` and using them with `nestjs/graphql`.

Since the second paragraph mentions that `type-graphql` is used under the hood, and resolvers and mutations were working fine at first (If you do your imports from `typegraphql` which the docs also show in the section about [object types](https://docs.nestjs.com/graphql/resolvers-map#code-first)), I was kind of expecting I could just follow their documentation and examples about subscriptions and resolvers.

Things that confused me:

- Using the `@Subscription` decorator from `type-graphl` didn't work because it expected an async iterator, so eventually I tried the `@Subscription` decorator from `nestjs/graphql`, but then it didn't recognise the `topics` property.
- In `type-graphql` you can just return an object-type from your subscription, but in `nestjs/graphql` you have to manually create an instance of `PubSub` and return an asyncIterator. Then it seems you have to provide the return type of that subscription in a payload object with a key that has the same name as the subscription, although by looking at the documentation, it looks like they are matched by triggerName (the publish method is not shown). Also, it seems there isn't really a way to strictly type the payload that you pass to `.publish(triggerName, { subscriptionName: payload })`?
- `FieldResolver` doesn't exist in `nestjs/graphql` but does work if you import `FieldResolver` and `Root` from `type-graphql` which is probably not the way to go.

## Expected behavior
I understand that these are 2 different packages but at first glance it looks like nestjs only offers a thin layer on top of typegraphql, which is not the case if you dig a little deeper.

Maybe the documentation could expand a bit on these differences, and explain why in some cases a different approach was chosen?

## Environment

<pre><code>
Nest version: 6.7.2

For Tooling issues:
- Node version: v11.15.0
- Platform:  Mac
</code></pre>

**Comment by kamilmysliwiec** [comment]
Fixed in https://github.com/nestjs/docs.nestjs.com/pull/1053 (type-graphql is no longer being used)
