### ISSUE TITLE
Pipe transform options explanation says opposite of code

### ISSUE THREAD

**Issue by Y0hy0h** [nestjs/docs.nestjs.com#83]
In the [pipe doc](https://docs.nestjs.com/pipes) under *A built-in ValidationPipe*, the text talks about enabling transformation:

> However, if you want the pipe to mutate the payload, you can configure it by passing appropriate options: 

But the code has transformation disabled:

> `@UsePipes(new ValidationPipe({ transform: false }))`

The source code for the doc explicitly calls the code for [`createCatsControllerParamPipeTransformFalse `](https://github.com/nestjs/docs.nestjs.com/blob/master/src/app/homepage/pages/pipes/pipes.component.html#L283). So I am unsure whether there is a reason for the code to be this way. If the code is meant to be this way, then the text should reflect that the code does *not* transform.

But personally, I would prefer changing the code to show transformation, since that wasn't happening in the doc before.

**Comment by kamilmysliwiec** [comment]
Fixed, I'll push update soon
