### ISSUE TITLE
Authentication Tutorial always returns 401 Unauthorized after implementing local strategy

### ISSUE THREAD

**Issue by labcorp-clinical-development** [nestjs/docs.nestjs.com#875]
## Current behavior
Work through the steps on the Authentication tutorial until you complete the "Login Route" step.

## Input Code
https://docs.nestjs.com/techniques/authentication

## Expected behavior
When POSTing valid user credentials to /auth/login, the user should be returned as part of the response.

I have verified that my user's credentials are correct and that my MongoDB query works as expected when executed against the collection of User objects.

However, a 401 unauthorized is always returned.

## Environment
Any

<pre><code>
Nest version: X.Y.Z

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
cc @johnbiundo

**Comment by johnbiundo** [comment]
@labcorp-clinical-development Do you have a minimal reproduction of this issue?

**Comment by labcorp-clinical-development** [comment]
Hi @johnbiundo. I do in a private Gitlab repo. I'm fairly busy at the moment, but let me try to find some time this evening to get a publicly available repo to you.

I'm using MongoDB + Mongoose for database connectivity and "email" for the "username" field.

It seemed to be a combination of the method I was using to retrieve the user, and also changing the PassportStrategy. Given that removing the strategy makes the application work, the bug has to be related to my service method.

**Comment by johnbiundo** [comment]
@labcorp-clinical-development Sure thing.  It would be great to reduce it to a minimal case.  I would start by removing the dependency on MongoDB (e.g., hard code user info) to eliminate that variable and to make the repro test case simple to work with.

**Comment by leosuncin** [comment]
@johnbiundo a failing example is here https://github.com/leosuncin/nest-auth-example but only with node.js version greater than 13.0.0, in the previous versions works well

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/issues/3631

**Comment by thierri** [comment]
The problem is the signature of **validate** method, on LocalStrategy class. Make sure it receives exactly **username** and **password**. 

If you replace username with email or something else it will not overload the original PassportStrategy method, returning always Unauthorized, given no clue of the error. 

`
 async validate(username: string, password: string): Promise<any> {
     // Do any validation here.
  } 
`

**Comment by jmcdo29** [comment]
The docs do say this:
> We've also implemented the `validate()` method. For each strategy, Passport will call the verify function (implemented with the `validate()` method in `@nestjs/passport`) using an appropriate strategy-specific set of parameters. For the local-strategy, Passport expects a `validate()` method with the following signature: `validate(username: string, password:string): any`.

About three paragraphs above [here](https://docs.nestjs.com/techniques/authentication#built-in-passport-guards)
