### ISSUE TITLE
Nest mvc documentation and sample code needs updating

### ISSUE THREAD

**Issue by Zephilim** [nestjs/docs.nestjs.com#90]
The issue I have found is not made apparent until the e2e tests are run.

It is not made clear in the documentation (https://docs.nestjs.com/techniques/mvc) where the "views" and the "public" folders should be created. I assumed that they should both go into "src" folder because main.ts is located in "src" and it refers to 'public' and 'views' when it performs a 'join'.

When you run the e2e tests (npm run test:e2e) you see a message similar to this:

> [Nest] 20785   - 2018-6-13 15:31:19   [ExceptionsHandler] ENOENT: no such file or directory, open '/Users/Plastikfan/dev/git/citrus/seed/adminpro-nest/nest-server/src/views/index.hbs'

I changed main.ts to the following (assuming that "public" and "views" are in project root and not "src"):

```
async function bootstrap() {
  const app = await NestFactory.create(AppModule, new FastifyAdapter());

  app.useStaticAssets({
    root: join(__dirname, '../public'), // NB: ../
    prefix: '/public/',
  });
  app.setViewEngine({
    engine: {
      handlebars: require('handlebars'),
    },
    templates: join(__dirname, '../views'), // NB: ../
  });

  await app.listen(3000);
}

**Comment by kamilmysliwiec** [comment]
Fixed. I'll push update very soon
