### ISSUE TITLE
docs: Run only one command for HMR

### ISSUE THREAD

**Issue by Hwan-seok** [nestjs/docs.nestjs.com#915]
## I'm submitting a...

<pre><code>
[x] Documentation issue or request 
</code></pre>

## Current behavior

To use HMR,
[Hot Module Replacement(HMR) document](https://docs.nestjs.com/recipes/hot-reload) says 

add two scripts to your  `package.json`  file. (focus on using nest cli)
```json
"build": "nest build --watch --webpack"
"start": "node dist/main",
```
open your command line and run the following command:
```bash
npm run build
```
and open another command line and run:
```bash
npm run start
```
## Expected behavior

But it can be a little confusing to one who have no experience about HMR or have less skills like me ..
Additionally, If my experience is right, docker cannot run two command line at the same time.
So I suggest improvement of this document.

### As is
- Have to run two command at the seperated command lines

### To be
- Can  **run only one command at one command line**

### Through
- `onBuildEnd` option of `WebpackShellPlugin`

After apply this feature:
open your command line and run the only following command:
```bash
npm run build
```

I will make a pull request very soon
## Environment

<pre><code>
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by Hwan-seok** [comment]
### Conflict
It seems default `nest start` command processes webpack build too.
It hooks that i suggested(`onBuildEnd`)

### Solution
Compile nest app through tsc not webpack, it will be operates normally(`nest start --tsc` )

---
I think we need to change the default compiler to tsc or we can write in the documentation to choose how to start the nest application.
1. use past version (using two command lines)
2. use my suggestion (using one command line and use tsc to normal start)

Please feel free to suggest about it!

**Comment by MajdTaweel** [comment]
Hello Hwan-seok, the best workaround I found is the following:
After setting up HMR as instructed in Nest docs, install "npm-run-all" and "wait-on" by executing "npm install npm-run-all --save-dev" and "npm install wait-on".
Then, in your package.json add the following scripts:
```
    "prebuild": "rimraf dist",
    "build:webpack": "nest build --watch --webpack",
    "start:hmr": "wait-on dist/main.js && node dist/main",
    "hmr": "npm-run-all prebuild -p -r build:webpack start:hmr"
```
Then, execute "npm run hmr". And that's all.
The "hmr" script firstly deletes the dist folder. Then it runs "build:webpack" and "start:hmr" in parallel. The "start:hmr" waits for dist/main.js files creation and then executes, and that would be after it is build using webpack. So, even though "build:webpack" and "start:hmr" runs in parallel, "node dist/main" in "start:hmr" won't run until dist/main.js is created. Usually, "node dist/main" runs faster than "nest build --watch --webpack", and that would always result in the script not running as expected. This justifies the need to firstly delete the dist folder and then wait until dist/main.js is created and the run "node dist/main". Hopes this was helpful.

**Comment by Hwan-seok** [comment]
Thanks! @Majd Taweel
Your way is better than mine. 
It would be nice because we don't have to change codes 

I'll close this issue
 
-----Original Message-----
