### ISSUE TITLE
Docs don't build

### ISSUE THREAD

**Issue by xcambar** [nestjs/docs.nestjs.com#93]
Hello there,
after checking out the repo and `npm install`ing, when I run `$ npm start` I get the following message after which everything stops:

```
It seems like you're using a project generated using an old version of the Angular CLI.
The latest CLI now uses webpack and has a lot of improvements including a simpler
workflow, a faster build, and smaller bundles.

To get more info, including a step-by-step guide to upgrade the CLI, follow this link:
https://github.com/angular/angular-cli/wiki/Upgrading-from-Beta.10-to-Beta.14
```

I don't have anglular-cli installed globally, so it comes directly from the package itself.

Has anyone already encountered this? Am I doing something wrong?

**Comment by kamilmysliwiec** [comment]
Honestly, I cannot reproduce this issue locally.
