### ISSUE TITLE
Typo In gateways doc examples

### ISSUE THREAD

**Issue by bradtaniguchi** [nestjs/docs.nestjs.com#95]
I found a small typo in the gateways doc examples in the Asynchronous responses section.

The code in the example is as followed:
```typescript
@SubscribeMessage('events')
onEvent(client, data: any: Observable<WsResponse<number>> {
  const event = 'events';
  const response = [1, 2, 3];

  return from(response).pipe(
    map(data => ({ event, data })),
  );
}
```
The onEvent function seems like its missing its closing `)` character after `data: any`.

Issue within the code is found at this [line](https://github.com/nestjs/docs.nestjs.com/blob/2889295c714d264e6b9380c3d75432bc5f8a7ace/src/app/homepage/pages/websockets/gateways/gateways.component.ts#L49) 

thanks for all the work done on NestJs, so far loving the framework 👍 😄

**Comment by kamilmysliwiec** [comment]
Thanks @bradtaniguchi! Fixed, will push soon
